### ISSUE TITLE
Installation issues on WP CiviCRM site

### ISSUE THREAD

**Issue by ghost** [drastik/com.drastikbydesign.stripe#1]
Cross-posted in the CiviCRM Installation Help forum as well:

Sadly the documentation has left me confused and the installation process has stalled. 

It is unclear to me where in the chain of relationships the errors are occurring. When I attempt to test from the Stripe.com Account management page the URI to the Webhook.php file, WP returns a 500.

Is there a debug log in CiviCRM which will show me what errors the stripe.php et al. are throwing ?  I'm very new to CiviCRM but can find my way around WP generally. And I am a PHP developer full time, for background.

Any assistance appreciated.
~ Erik

**Comment by ghost** [comment]
Resolved.

**Comment by drastik** [comment]
Oh wow sorry, I did not see this previously.

If I may ask, what was the problem and what was your solution?

**Comment by ghost** [comment]
Don Lobo was kind enough to point me to the wp-content/plugins/files/civicrm/ConfigAndLog directory.

I also discovered by trial an error that the WP environment wants the Webhook.tpl file not the Webhook.php file as the target of the API callback setup in the Stripe Account > Webhooks panel.

Now, happily, transaction testing s working great.  Thanks for the work you've done on this. I hope this explanation can help with your docs.

**Comment by awkale** [comment]
@roaringskysoftware did you place any file in wp-content/plugins/files/civicrm/ConfigAndLog
what path did you put in the stripe webhook panel?

I keep getting 500 errors
