### ISSUE TITLE
Recurring contribution assumes a number of installments

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#10]
When submitting a recurring contribution without a set number of installments I receive the following error:

![newerror](https://f.cloud.github.com/assets/3266985/1188762/f860c0c4-23e6-11e3-9d97-0ed73f3b0344.png)
1. https://github.com/drastik/civicrm_stripe/blob/4.3-1.7/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php#L404

``` php
$installments = $params['installments'];
```
1. https://github.com/drastik/civicrm_stripe/blob/4.3-1.7/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php#L467-L481

``` php
// Calculate timestamp for the last installment.
    $end_time = strtotime("+$installments $frequency");
    $invoice_id = $params['invoiceID'];

    // Prepare escaped query params.
    $query_params = array(
      1 => array($stripe_customer->id, 'String'),
      2 => array($invoice_id, 'String'),
      3 => array($end_time, 'Integer'),
    );

    // Insert the new Stripe Subscription info.
    CRM_Core_DAO::executeQuery("INSERT INTO civicrm_stripe_subscriptions
(customer_id, invoice_id, end_time, is_live)
VALUES (%1, %2, %3, '$transaction_mode')", $query_params);
```

**Comment by kcristiano** [comment]
I am experiencing the same issue on CiviCRM 4.3.7.  DaveBagler seems to have hit the nail on the head that a recurring payment with no end date causes the above error.

Have you been able to replicate this and are there a plans for an update?

**Comment by drastik** [comment]
I can't get to it at this time.  Still waiting for life to slow down long enough to have free time.

That said, patches are 100% welcome!  I will pull them in github & create new release in Civi's repo immediately.

**Comment by joetri** [comment]
I'm seeing the same issue. CiviCRM  4.3.7,  extension downloaded via the zip file (4.3-1.7.zip), Drupal 7.17 Commerce Kickstart Profile. I've got the Drupal Module CiviCRM Stripe enabled, which I think is wrong. I'll test with that off.

Are we looking for a default value here? If so what's a reasonable default 1 month from now, 1 year from now? And how do we code it in. I've got a nice test environment up for testing this.

**Comment by kcristiano** [comment]
I would think that if we are required to put a value I would set it as 99.  That way it would recur until cancelled (or until 99 months/weeks/years are exhausted)

**Comment by drastik** [comment]
In Stripe, the 'subscription' (customer assigned to a plan that is taking regular payments), does not have an end date.  If memory serves, CiviCRM also has the ability to recognize a no-end-date recurring contribution.

The solution here should be to anticipate a no-ending recurring contrib, and handle slightly different -- put 0 as end_time in civicrm_stripe_subscriptions table and just ignore those w/ 0 end on the webhook updates.

**Comment by drastik** [comment]
Rather, to be more clear, not ignore (because Civi still needs to make the update of the funds coming in), but ignore from the "do I need to end this subscription now" portion of Webhook.

This will solve the DB error about end_time value not being integer (we set to 0).

**Comment by joetri** [comment]
If line 404 gets added to like below (untested), would that put in 99 as the default number of renewals for a recurring payment? Not sure this is the best way, but if it beats the bug, that's good ay? Who wants recurring payments to go on forever?

``` php
$installments = $params['installments'];
if ( !isset($params['installments'] ) || ( $params['installments']==0 ) ){
    $params['installments'] = 99;
}
```

**Comment by joetri** [comment]
Can confirm that hardcoding in the $end_time for Jan 1, 2023 on line 475 of the 1.7 release as below works and removes error: "... not of type Integer". Slightly different approach to the one I outline above, but same general idea.

``` php
    3 => array(1672531200, 'Integer'),
```

I know this may not be the Right Thing to do, but it might be helpful to troubleshooters.
Note that Civi reports this recurring contribution as status "Pending (Incomplete Transaction)" and Stripe records this as a clean completed payment. 

Drupal 7.17 Commerce Kickstart Install Profile, CiviCRM 4.3.7, Stripe PHP Library Version 1.7.1, CiviCRM_Stripe Extension 4.3-1.7, PHP 5.3.26.

**Comment by DaveBagler** [comment]
I ended up hard coding the number of installments to 60 months and that gets me around the issue.  @drastik I'll try to get a patch together soon (haven't had time yet).

**Comment by joetri** [comment]
Seems like this is solved in the latest release. In my testing I no longer error out with the base release code.

**Comment by joetri** [comment]
Wait: take that back. No longer erroring with the "... not of type Integer" white screen message. So this appears to be a smooth transaction. On further inspection logs show 

>   Notice: Undefined index: installments in >CRM_Core_Payment_Stripe->doRecurPayment() (line 404 of /BASE_DIR
> /sites/default/files/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core
> /Payment/Stripe.php).

So it appears error treatment has changed, but error still extists?
