### ISSUE TITLE
Error triggered by recurring payment

### ISSUE THREAD

**Issue by h-c-c** [drastik/com.drastikbydesign.stripe#104]
A successful stripe payment was made, but the user got this error that makes reference to a recurring payment, which he opted for.   Any idea why this is happening? I assume the recurring payment won't be made next cycle. 

Thanks!

Strict warning: Accessing static property CRM_Core_Payment_Stripe::$_mode as non static in CRM_Core_Payment_Stripe->doRecurPayment() (line 467 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-1.9.1/com.drastikbydesign.stripe-1.9.1/CRM/Core/Payment/Stripe.php).

Notice: Undefined property: CRM_Core_Payment_Stripe::$_mode in CRM_Core_Payment_Stripe->doRecurPayment() (line 467 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-1.9.1/com.drastikbydesign.stripe-1.9.1/CRM/Core/Payment/Stripe.php).

Notice: Undefined index: installments in CRM_Core_Payment_Stripe->doRecurPayment() (line 477 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-1.9.1/com.drastikbydesign.stripe-1.9.1/CRM/Core/Payment/Stripe.php).

Notice: Use of undefined constant Stripe_InvalidRequestError - assumed 'Stripe_InvalidRequestError' in CRM_Core_Payment_Stripe->doRecurPayment() (line 504 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-1.9.1/com.drastikbydesign.stripe-1.9.1/CRM/Core/Payment/Stripe.php).

Notice: Undefined variable: transaction_mode in CRM_Core_Payment_Stripe->doRecurPayment() (line 579 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-1.9.1/com.drastikbydesign.stripe-1.9.1/CRM/Core/Payment/Stripe.php).

**Comment by drastik** [comment]
Should be fixed.  To be sure your data is correct, check the `civicrm_stripe_plans` &/or `civicrm_stripe_subscriptions` table for the `is_live` column on that contribution.
Possible values for that column:

```
Live = 1
Test = 0
```

**Comment by h-c-c** [comment]
is_live was 0, I switched it to 1 manually for that contributor.  I updated to the most recent git version, and tried a new recurring contribution.  Again the payment went through, but with these errors below and is_live was 0 again.

Thanks for looking into this!  

Strict warning: Accessing static property CRM_Core_Payment_Stripe::$_mode as non static in CRM_Core_Payment_Stripe->doDirectPayment() (line 260 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined property: CRM_Core_Payment_Stripe::$_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 260 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined variable: transaction_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 347 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined variable: transaction_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 404 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined index: transaction_mode in CRM_Core_Payment_Stripe->doRecurPayment() (line 554 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined index: installments in CRM_Core_Payment_Stripe->doRecurPayment() (line 558 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Use of undefined constant Stripe_InvalidRequestError - assumed 'Stripe_InvalidRequestError' in CRM_Core_Payment_Stripe->doRecurPayment() (line 586 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

**Comment by drastik** [comment]
https://github.com/drastik/com.drastikbydesign.stripe/commit/4ee7e494ca2bf6494f281c6c6fd0bb29c2fe766e
