### ISSUE TITLE
Error after payment

### ISSUE THREAD

**Issue by h-c-c** [drastik/com.drastikbydesign.stripe#106]
This is an error generated after a regular non-recurring payment:

Strict warning: Accessing static property CRM_Core_Payment_Stripe::$_mode as non static in CRM_Core_Payment_Stripe->doDirectPayment() (line 260 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined property: CRM_Core_Payment_Stripe::$_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 260 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined variable: transaction_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 347 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Notice: Undefined variable: transaction_mode in CRM_Core_Payment_Stripe->doDirectPayment() (line 404 of /home/username/www/www/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php).

Any ideas what's happening? 
Thanks much

**Comment by Upperholme** [comment]
Looks like a warning rather than an error. Maybe related to code written for an older version of PHP running under a newer version - that kind of thing can often lead to strict warnings.

**Comment by drastik** [comment]
It also doesn't return the proper value.  I think something changed in recent Civi version.
Have to find where we can get the live/test mode information now.

**Comment by drastik** [comment]
Large update just released.  Will update CiviCRM repos once I figure 1 last thing out.

https://github.com/drastik/com.drastikbydesign.stripe/commit/4ee7e494ca2bf6494f281c6c6fd0bb29c2fe766e
