### ISSUE TITLE
civicrm_stripe tables dropped 

### ISSUE THREAD

**Issue by h-c-c** [drastik/com.drastikbydesign.stripe#108]
During my last upgrade, I seem to have experienced a dropping of existing civicrm_stripe tables and recreation of empty tables.  Going from the 1.9.1 to 4.6-dev didn't affect the existing stripe transaction data.  I'm not entirely sure if I went about the upgrade the same way.  Is it possible that uninstalling the module dropped those tables?  If so, is there some upgrade method I was supposed to do that does not do this. Or can it just not ever do that?   I didn't see any option during uninstallation to keep or remove data.  

Thanks

**Comment by drastik** [comment]
CiviCRM follows Drupal's terminology and usage in this regard; _Disable_ leaves the tables, _Uninstall_ removes the tables.

Ultimately though, it is up to the extension, and what it defines in its enable, disable, and uninstall hooks.  In civicrm_stripe's case, it still follows the standard pattern mentioned above.

**Comment by h-c-c** [comment]
Thanks, I closed this because I realized I missed the warnings at uninstall time.  The civi docs don't seem make it too clear how to upgrade a module outside of the regular channel.  (click to upgrade)
