### ISSUE TITLE
remove reference to minicvv_2.gif no longer in CiviCRM (4.3 or 4.4)

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#11]
in /templates/CRM/Core/BillingBlock.tpl, the image source is listed as:
 $config->resourceBase}i/mini_cvv2.gif

As part of the work done on http://issues.civicrm.org/jira/browse/CRM-12515, mini_cvv2.gif was removed from the CiviCRM core repository. The Stripe extension points to the non-existing file.

**Comment by arborrow** [comment]
https://github.com/colemanw/civicrm-core/commit/4f7f49d54a778005515ee984b90fc13430e8f63e shows how they are handling cvv image now:

+#crm-container .cvv2-icon {
-  display: inline-block;
-  width: 50px;
-  height: 30px;
-  background: url(../i/creditcard-icons.png) no-repeat 0 0 transparent;

**Comment by drastik** [comment]
Thank you

**Comment by drastik** [comment]
Fixed in latest 4.4 commit.
