### ISSUE TITLE
Wrong transaction ID and missing fee for recurring payments

### ISSUE THREAD

**Issue by BorislavZlatanov** [drastik/com.drastikbydesign.stripe#110]
In Core/Payment/Stripe.php, in doDirectPayment(), on line 473 there is `$stripe_response = $this->stripeCatchErrors('charge', $stripe_charge, $params);`

Then by doing `$params['trxn_id'] = $stripe_response->id;` we get the correct transaction ID. 

And finally, with `$balance_transaction = $this->stripeCatchErrors('retrieve_balance_transaction', $stripe_response->balance_transaction, $params);` and then `$params['fee_amount'] = $balance_transaction->fee / 100;` we get the stripe fee.

All of that seems to work right. However, in doRecurPayment() we have `$stripe_response = $stripe_customer->updateSubscription($cust_sub_params);`, which seems to be a different animal. 

At the end of the doRecurPayment() method, `$params['trxn_id'] = $stripe_response->id;` gives us what I think is the subscription ID rather than the transaction ID. Also, `$stripe_response->fee` seems to be empty, so it doesn't get set in the `$params` array. In doDirectPayment() we got the fee using 'retrieve_balance_transaction'. Maybe the same needs to be done for recurring payments?

Any thoughts on this?

**Comment by drastik** [comment]
Stripe's API is very nice for looking at the provided/returned values for their methods.  You are probably correct.

I will have a peek when I work on Stripe next.
