### ISSUE TITLE
Feature request:  Recurring contribution for membership should update membership. 

### ISSUE THREAD

**Issue by h-c-c** [drastik/com.drastikbydesign.stripe#119]
Because I need recurring contributions for membership ASAP, I've removed campaign_id from Webhook.php. (in parameter setup and INSERT portions)  We don't use campaign_ids, and currently there's a dammed-if-you-do dammed-if-you-don't situation with setting campaign_id as a NULL or Integer.  See https://github.com/drastik/com.drastikbydesign.stripe/issues/92, https://github.com/progressivetech/com.drastikbydesign.stripe/commit/6f311003cf068f7d4a5e48b22c840258585a4974, https://github.com/drastik/com.drastikbydesign.stripe/issues/117. 

Good news, I have a contribution recorded that was created with Webhook.php!  The bad news for us is that it's not updating a members status and membership end-date.  FWIW, I'm having the same problem when I create a contribution with the api, referencing a contribution_page_id, like so:

```
$result = civicrm_api3('Contribution', 'create', array(
  'sequential' => 1,
  'financial_type_id' => "Member Dues",
  'total_amount' => 1,
  'contact_id' => 2,
  'contribution_page_id' => 3,
));
```

I'm really hoping this isn't a larger CiviCRM problem!   It seems like we have to send Stripe some info that says, "This subscription is for membership_id=x", then they should send it back when the payment happens.  Is that sensible? Looking at the event data on Stripe.com doesn't show me anything like that for the recurring payments I've had so far.  

ps. I could be wrong, but I don't think removing campaign_id in Webhook.php is the cause of this.  
pps. After looking at what CiviCampaign does, maybe I do need this!  

Any insight would be appreciated!

**Comment by BorislavZlatanov** [comment]
Well, it seems like you should be operating with memberships, not contributions (even though memberships are considered a type of contribution, I think).

I haven't worked with memberships at all, but here are a few thoughts. 

You need a membership signup form on which the payment processor is stripe. 

The stripe.com site doesn't need to know anything about your memberships, it cares only about payments. You decide what those payments are used for (memberships, events, etc.).

If you can't get it to work out of the box (with a membership signup form) and you think you have to write code, then you need to be looking at the membership entity, e.g. 

```
$result = civicrm_api3('Membership', 'create', array(
  'sequential' => 1,
  'membership_type_id' => "",
  'contact_id' => "user_contact_id",
));
```

Go to http://dmaster.demo.civicrm.org/civicrm/api/explorer (login is demo/demo) and take a look at the API explorer.

**Comment by h-c-c** [comment]
Hey Boris, let me tell you about the workflow in CiviMember.  It lets an org set up a contribution page for memberships.  Before the page can be created, membership levels must be defined.  (how long, what cost, etc.)  The contribution page gives options for what payment processors are used, if recurring payment is allowed, and it also lets orgs present these contribution pages as online forms that users can have direct access to for joining. When a contribution is made through the online membership contribution page,  a membership record is created or updated, which touches the member status_id and sets an end date appropriate to which level the user payed for.  So the contribution is responsible for the membership.   Thanks, I've seen the api explorer....that's where the code came from that I posted originally.  Like I said, I've used the api to create a contribution, but it won't change the membership records if I merely reference the contribution_page_id.....there must be more to it.  

This is what we do and how our members keep themselves up to date.  This Stripe extension is what we use on the membership contribution page.  When a user makes a membership contribution through the membership contribution page, no one has to manually go in and set the membership status_id and end-date.  That would be ridiculous, and untenable.  So when users opt for recurring payments on their memberships, the same things should happen automatically.   Having to adjust those records manually would be a deal breaker for us and I'd be surprised if other orgs would settle for that.  I could see a post hook module taking care of this actually.  Seems kind of hacky though.

**Comment by h-c-c** [comment]
I could be wrong, but It looks like this functionality wasn't included.   It seems only natural that a recurring contribution would do the same things in civi that the original contribution did.  For organizations that have memberships, this is huge.  Not that peer pressure is necessarily a good reason to do something, but it appears that other payment processor extensions for CiviCRM handle this.    <br> <br> Is adding this feature something that seems worthwhile do you folks?  Because we only use recurring contributions for memberships, I could just as easily spend my efforts on a helper module to accomplish this...but that's pretty self-centered. I'd like to contribute to the project in some way if there's interest.  If not, the module the helper module would be much faster for me to work up.  <br><br>    Does anyone have feelings about this?   I think I might know where Boris stands.  ;-)

Here's my thoughts anyway on how it would work.  A new column would get added to civicrm_stripe_plans called membership_type_id.  I think that would be a foreign key to civicrm_membership_type - id column.  It would be an integer, zero for 'not-a-membership'.   During plan subscription, the membership_type_id=x gets sent as metadata to stripe.  Stripe sends it back when payments are made -> all the right stuff happens to memberships if membership_type_id > 0.   I'm not sure how all the right stuff happens....I don't know if there's meta way of processing the membership.  If it's manual, the membership end date and membership status get touched.   membership end date can be derived form membership type id.

**Comment by Upperholme** [comment]
If this payment processor wants to be useful for CiviCRM then it has to work with CiviCRM and do everything that CiviCRM expects a payment processor to do. As you say h-c-c, not supporting membership renewals effectively is a total deal breaker.

**Comment by h-c-c** [comment]
This functionality was added when we started using the api for processing recurring contributions.  Sorry, I should have closed this earlier.
