### ISSUE TITLE
Strict warnings

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#12]
Just to document a couple of strict warnings I observed on a site in the hopes of cleaning things up when there is time (FYI, I am running the Stripe extension under CiviCRM 4.4.0),

•Strict warning: Declaration of CRM_Core_Payment_Stripe::singleton() should be compatible with & CRM_Core_Payment::singleton($mode, &$paymentProcessor, &$paymentForm = NULL, $force = false) in require_once() (line 5 of /home2/ignatia1/public_html/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php).

•Strict warning: Accessing static property CRM_Core_Payment_Stripe::$_mode as non static in CRM_Core_Payment_Stripe->__construct() (line 32 of /home2/ignatia1/public_html/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php).

**Comment by elliphant** [comment]
Any update on this? Just wanted to flag that I'm getting a similar issue (updated to civicrm 4.4.3):
- Strict warning: Declaration of CRM_Core_Payment_Stripe::singleton() should be compatible with & CRM_Core_Payment::singleton($mode, &$paymentProcessor, &$paymentForm = NULL, $force = false) in CRM_Core_Payment::singleton() (line 112 of /../sites/all/modules/civicrm/CRM/Core/Payment.php).
- Strict warning: Accessing static property CRM_Core_Payment_Stripe::$_mode as non static in CRM_Core_Payment_Stripe->__construct() (line 32 of /../sites/default/files/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php).

**Comment by arborrow** [comment]
Are you using the 1.6 or 1.7 version of the Stripe extension?

**Comment by elliphant** [comment]
Stripe extension: 1.7, with drupal 7.24 and civicrm 4.4.3.

**Comment by drastik** [comment]
What are you doing when you get this error?

**Comment by arborrow** [comment]
It has been a while and I just turned off the errors in Drupal but I believe it was in registering for an event although at the moment I cannot reproduce it. Perhaps elliphant can provide more details. If not, I will poke around and see what I can do to reproduce it. Peace - Anthony

**Comment by elliphant** [comment]
I get the error when I set up a contribution page with the stripe payment processor and then navigate to the page. Also get it when an event it set up to collect fees with the payment processor, and then I try to register for that event. (So, basically it shows up whenever it would be used).  Reinstalled fresh installs tonight and reproduced the error.  Thanks for any help!
-Elliot

**Comment by drastik** [comment]
I need to look at latest Civi codebase.  Sounds like the parent payproc class has changed it's structure.

**Comment by drastik** [comment]
Give it a shot w/ latest update.  Civi core changed the singleton/constructor for payprocs.
https://github.com/drastik/civicrm_stripe/commit/021e9a6d89b11b553965838f4eae1c05b6a65e87

**Comment by drastik** [comment]
Issues solved for latest Civi 4.5-1.8
