### ISSUE TITLE
What commit should I be using?

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#125]
If I use the latest commit I get a session error because the contribution page looses the ID chain.
If I use earlier commits I can get the contributions to work but webhooks for recurring contributions don't work (no receipt, pending.)

**Comment by drastik** [comment]
Unfortunately I haven't been able to test in a while.

When you say:

> looses the ID chain.

Are you talking about the contribution Page ID (as in the URL var)?  Or the stripe-token?

**Comment by DaveBagler** [comment]
Here's the stack exchange question I asked about it before I narrowed it down to being the Stripe-Civi plugin. http://civicrm.stackexchange.com/questions/8591/session-key-issues-after-upgrading-from-4-4-to-4-6
