### ISSUE TITLE
Test secret/publishable keys get overwritten with live keys on payment processor configuration save

### ISSUE THREAD

**Issue by richardsplayground** [drastik/com.drastikbydesign.stripe#133]
When I go to configure my Stripe payment processor (https://site/civicrm/admin/paymentProcessor), the form has fields for:
- Live Secret Key
- Live Publishable Key
- Test Secret Key
- Test Publishable Key

I input the values provided by the Stripe dashboard under my account settings.  All four values are different, and the keys clearly identify whether they are for test or live, so I know I'm putting right values in the right fields.

When I hit save, the test secret key gets overwritten by the live secret key, and the test publishable key gets overwritten by the live publishable key.  No matter how many times I go in to edit the payment processor configuration, re-enter the correct test values, and re-save, the next time I edit the payment processor the test values are overwritten by the live values.

I have also tried creating a totally brand new payment processor configuration -- same result.

The net result is that I cannot run test transactions because Stripe sees me using a live key for a test customer.

I'm not sure if this is an issue with my CiviCRM install or an issue with the civicrm_stripe plugin.  I pulled the latest plugin version as of today and am on a newly upgraded CiviCRM 4.7.1.

Thanks

**Comment by Iteratix** [comment]
I'm having this issue also, richardsplayground, and I think it's with CiviCRM. I happened to have the Stripe extension enabled, but was seeing the Test keys being overwritten with Live keys with PayPal payment processors. I thought it might be because of the Stripe extension, so I disabled it -- but I'm still seeing the behavior.

**Comment by richardsplayground** [comment]
Thanks @Iteratix.  I am glad to hear I was not doing something totally stupid.  I have reported the issue to the CiviCRM team: https://issues.civicrm.org/jira/browse/CRM-18061

**Comment by Iteratix** [comment]
Great! I was going to look into that next. Thanks for confirming and posting the Jira issue.

**Comment by h-c-c** [comment]
I have a patch that fixes this issue:

https://github.com/h-c-c/civicrm-core/commit/507e7942c0dbbeebd6321c08b3be659f7b45866a

**Comment by h-c-c** [comment]
This issue is fixed upstream. https://github.com/civicrm/civicrm-core/pull/7914
