### ISSUE TITLE
Compatibility with CiviCRM 4.7.x?

### ISSUE THREAD

**Issue by Upperholme** [drastik/com.drastikbydesign.stripe#136]
Hi. Anyone using this extension with Civi 4.7.x with success (or otherwise)?

**Comment by drastik** [comment]
I have issues with `civicrm_stripe.js` loading.

**Comment by richardsplayground** [comment]
I thought I was doing OK on Civi 4.7.x.  But I have recently run into this issue.

Payment Error Response: Error: The card object must have a value for 'number'

Possibly related to [this](http://civicrm.stackexchange.com/questions/10238/pay-later-option-on-4-7-2-using-stripe-doesnt-work-throwing-error), although I don't have "Pay Later" enabled.

And also possibly related to [this](https://github.com/drastik/com.drastikbydesign.stripe/issues/109).

I'm really beginning to think that with all of the javascript issues I run into every time I do an upgrade, it might be better to go with the [PHP submission model](https://github.com/drastik/com.drastikbydesign.stripe/pull/114).  (Which still seems to be not merged?)

**Comment by richardsplayground** [comment]
Should we (could we) start a 4.7-dev branch?

**Comment by laryn** [comment]
@richardsplayground Did you see the [comment I made at the bottom of the issue](https://github.com/drastik/com.drastikbydesign.stripe/issues/109#issuecomment-218236700) you linked? Not sure if yours is a similar issue or not but thought I'd flag it in case you hadn't read that thread all the way through.

Personally I want to keep the Javascript submission to keep the PCI benefits, would just like to solve the issues! But I'm not opposed to others using PHP if they want to...
