### ISSUE TITLE
JS references payment_processor radio button with wrong name attribute

### ISSUE THREAD

**Issue by smoyte** [drastik/com.drastikbydesign.stripe#142]
I'm new to this so forgive me if I'm wrong, but it seems that in the contribution form in the latest CivicCRM code, the payment processor radio buttons use a `name` of `payment_processor_id`:

https://github.com/civicrm/civicrm-core/blob/2e47d34e2cabae7655085a611fdf8c54debbb8f8/CRM/Contribute/Form/Contribution/Main.php#L331

Yet, in the `civicrm_stripe.js` file, it is looking for `payment_processor`. 

https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/js/civicrm_stripe.js#L156

This was causing the dreaded 'no token sent' error for us. I wonder if it is for other folks?

I'm reluctant to submit a PR simply changing the field name since I'm not sure what the implications might be to other folks, so this is more of a question for now.

Thanks for all your work!!

**Comment by drastik** [comment]
Here is what I see in mine.  Let me double check against latest CiviCRM.

![selection_030](https://cloud.githubusercontent.com/assets/1258227/16434389/24f58432-3d55-11e6-87e0-f812b09bf7a1.png)

**Comment by drastik** [comment]
You are correct, and this is very good news.  If this payproc ID is correct, we can eliminate a lot of other crufty checking to ensure we should be processing a Stripe payment (in the case of multiple payprocs).

Feel free to submit PR for what you've done, and we'll build on top of that!

![selection_031](https://cloud.githubusercontent.com/assets/1258227/16435116/5834bb2a-3d59-11e6-81fe-8bdc78b48844.png)
