### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by w3geekery** [drastik/com.drastikbydesign.stripe#15]
I tried commenting on your blog but was told the spam filter was turned off and it wouldn't let me leave a comment.

Here's what I was trying to post:

I would like to note for Joomla 3.2/Civi 4.4 users using the 4.3-1.7 version of this extension, please make sure you uncomment the lines cc_name building lines (line ~210) and the card_details building lines (line ~253) in the Stripe.php file located in the directory [your_civi_extensions]/com.drastikbydesign.stripe/CRM/Core/Payment/

I wasted several hours trying to figure out why this was failing until I saw the note in that file around line 247.

Good luck!

**Comment by drastik** [comment]
Yes, that will work, but you are no longer utilizing Stripe's token security by doing so.  The cc_name was commented out because it is included in the token data so not needed unless bypassing like you are.

Mollom is off now -- has been acting weird lately.

**Comment by w3geekery** [comment]
Hi Joshua,

Thanks for responding, I appreciate it.

I was getting sql errors during the civi contact creation process from
civi's contribute/utils.php - the sql was failing because there was a
reference to the civicrm_contribution.id column in the line "LEFT JOIN
civicrm_note ON ( civicrm_note.entity_table = 'civicrm_contribution' AND
civicrm_contribution.id = civicrm_note.entity_id ) " but
civicrm_contribution was not part of the setup of the query (see query
below), so the query failed with an unknown column error.

All I know is that when I uncommented that code, it started to work?

stack trace:

Nov 13 11:36:50  [info] $Fatal Error Details = Array
(
    [message] => There was an error saving new customer within Stripe.  Is
Stripe down?
    [code] =>
)

Nov 13 11:36:50  [info] $backTrace = #0
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Error.php(320):
CRM_Core_Error::backtrace("backTrace", TRUE)
#1
/home/wirivers/public_html/media/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php(299):
CRM_Core_Error::fatal("There was an error saving new customer within
Stripe.  Is Stripe down?")
_#2
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Contribute/BAO/Contribution/Utils.php(230):
CRM_Core_Payment_Stripe->doDirectPayment((Array:57))_
#3
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(972):
CRM_Contribute_BAO_Contribution_Utils::processConfirm(Object(CRM_Contribute_Form_Contribution_Confirm),
(Array:57), (Array:47), "9", "1", "contribution", (Array:0))
#4
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Form.php(261):
CRM_Contribute_Form_Contribution_Confirm->postProcess()
#5
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/StateMachine.php(160):
CRM_Core_Form->mainProcess()
#6
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(60):
CRM_Core_StateMachine->perform(Object(CRM_Contribute_Form_Contribution_Confirm),
"next", "Next")
#7
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203):
CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Contribute_Form_Contribution_Confirm),
"next")
#8
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/packages/HTML/QuickForm/Page.php(103):
HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Confirm),
"next")
#9
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Controller.php(345):
HTML_QuickForm_Page->handle("next")
#10
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(323):
CRM_Core_Controller->run((Array:3), NULL)
#11
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(72):
CRM_Core_Invoke::runItem((Array:15))
#12
/home/wirivers/public_html/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(52):
CRM_Core_Invoke::_invoke((Array:3))
#13 /home/wirivers/public_html/components/com_civicrm/civicrm.php(85):
CRM_Core_Invoke::invoke((Array:3))
#14 /home/wirivers/public_html/components/com_civicrm/civicrm.php(11):
civicrm_invoke()
#15 /home/wirivers/public_html/libraries/legacy/component/helper.php(355):
require_once("/home/wirivers/public_html/components/com_civicrm/civicrm.php")
#16 /home/wirivers/public_html/libraries/legacy/component/helper.php(335):
JComponentHelper::executeComponent("/home/wirivers/public_html/components/com_civicrm/civicrm.php")
#17 /home/wirivers/public_html/includes/application.php(220):
JComponentHelper::renderComponent("com_civicrm")
#18 /home/wirivers/public_html/index.php(52): JSite->dispatch()
#19 {main}

query:

SELECT
contact_a.id AS contact_id,
contact_a.contact_type  AS `contact_type`,
contact_a.contact_sub_type  AS `contact_sub_type`,
contact_a.first_name  AS `first_name`,
contact_a.last_name  AS `last_name`,
contact_a.household_name  AS `household_name`,
IF ( contact_a.contact_type = 'Individual', NULL,
contact_a.organization_name ) AS organization_name,
`1-location_type`.id AS `1-location_type_id`,
`1-location_type`.name AS `1-location_type`,
`1-email`.id AS `1-email_id`,
`1-email`.email AS `1-email`,
`1-phone-1`.id AS `1-phone-1_id`,
`1-phone-1`.phone AS `1-phone-1`,
`Main-location_type`.id AS `Main-location_type_id`,
`Main-location_type`.name AS `Main-location_type`,
`Main-address`.id AS `Main-address_id`,
`Main-address`.street_address AS `Main-street_address`,
`Home-location_type`.id AS `Home-location_type_id`,
`Home-location_type`.name AS `Home-location_type`,
`Home-address`.id AS `Home-address_id`,
`Home-address`.city AS `Home-city`,
`Home-address`.postal_code AS `Home-postal_code`,
`Home-address`.state_province_id AS `Home-state_province_id`,
`Home-address`.country_id AS `Home-country_id`,
`Billing-location_type`.id AS `Billing-location_type_id`,
`Billing-location_type`.name AS `Billing-location_type`,
`Billing-email`.id AS `Billing-email_id`,
`Billing-email`.email AS `Billing-email`,
civicrm_note.note AS contribution_note,
civicrm_value_spouse_name_1.id AS civicrm_value_spouse_name_1_id,
civicrm_value_spouse_name_1.spouse_name_2_2 AS custom_2
FROM civicrm_contact contact_a
LEFT JOIN civicrm_address `Home-address` ON (`Home-address`.contact_id =
contact_a.id AND `Home-address`.location_type_id = 1)
LEFT JOIN civicrm_address `Main-address` ON (`Main-address`.contact_id =
contact_a.id AND `Main-address`.location_type_id = 3)
LEFT JOIN civicrm_email `1-email` ON contact_a.id = `1-email`.contact_id
AND `1-email`.is_primary = 1
LEFT JOIN civicrm_email `Billing-email` ON contact_a.id =
`Billing-email`.contact_id AND `Billing-email`.location_type_id = 5
LEFT JOIN civicrm_phone `1-phone-1` ON contact_a.id =
`1-phone-1`.contact_id AND `1-phone-1`.is_primary = 1
LEFT JOIN civicrm_location_type `1-location_type` ON (  (
`1-email`.location_type_id = `1-location_type`.id )OR (
`1-phone-1`.location_type_id = `1-location_type`.id ) )
LEFT JOIN civicrm_location_type `Billing-location_type` ON (  (
`Billing-email`.location_type_id = `Billing-location_type`.id ) )
LEFT JOIN civicrm_location_type `Home-location_type` ON (  (
`Home-address`.location_type_id = `Home-location_type`.id )  )
LEFT JOIN civicrm_location_type `Main-location_type` ON (  (
`Main-address`.location_type_id = `Main-location_type`.id )  )
LEFT JOIN civicrm_value_spouse_name_1 ON
civicrm_value_spouse_name_1.entity_id = contact_a.id
*LEFT JOIN civicrm_note ON ( civicrm_note.entity_table =
'civicrm_contribution' AND civicrm_contribution.id
http://civicrm_contribution.id = civicrm_note.entity_id ) *
WHERE  ( contact_a.id = 14 )
GROUP BY contact_a.id LIMIT 0, 25;

**Comment by pricejn2** [comment]
This is an existing issue with CiviCRM -- http://issues.civicrm.org/jira/browse/CRM-13878

**Comment by drastik** [comment]
@pricejn2 are you the Joe Price from that thread?  What is the status with that?  Could some of that be the cause for this payproc not working?

**Comment by pricejn2** [comment]
@drastik -- yup, that's me.  

There was a recent pull request submitted that is a better patch than the one I had posted -- https://github.com/civicrm/civicrm-core/pull/2729.  

As it stands now, the broken contribution_notes could impact a lot of areas.  From @w3geekery comment, the error was directly related to the missing contribution_note sql join.

**Comment by drastik** [comment]
Haha, what a simple patch.

If anyone applies the patch @pricejn2 is referencing and tests this payproc, please comment in here how it goes!

I should have some time free up next week to give it a shot as well.
