### ISSUE TITLE
Stripe is moving over from SHA-1, TLS 1.0, and TLS 1.1

### ISSUE THREAD

**Issue by guanhuan** [drastik/com.drastikbydesign.stripe#153]
Apparently stripe is going to drop support for SHA-1, TLS 1.0, and TLS 1.1. Not sure if this is affected as the init.php that requires patching is not included in the packages but here are the references and solution:

https://stripe.com/blog/upgrading-tls
https://support.stripe.com/questions/how-do-i-upgrade-my-stripe-integration-from-tls-1-0-to-tls-1-2

**Comment by drastik** [comment]
This is mostly changes on their end, and should not affect us.

> You won’t need to change your code, but might need to upgrade your operating system or packages. 
> 
> If you’ve upgraded your Stripe library and operating system in the past year, you probably won’t need to do anything.

They also said:

> To avoid any disruption, we’ll notify you directly if we expect your integration to be affected.

So I'd assume if your server is still transmitting via older methods, it will notify you somehow, whether via email or in Stripe account.
