### ISSUE TITLE
Documentation/installation: Cannot see the extension on the Manage Extensions page

### ISSUE THREAD

**Issue by SunyataZero** [drastik/com.drastikbydesign.stripe#160]
Hi, i'm running Drupal 7 with CiviCRM 4.7 and am having problems with the installation. The installation instruction says:

> For CiviCRM 4.4 & up:
> 1) Your CiviCRM 'Resource URLs' must be set to the extensions directory
> relative to Drupal/CRM base. Example: /sites/all/civicrm_extensions/
> NOT the full server path like /var/www/sites/all/civicrm_extensions/
> The admin page for Resource URLs is: /civicrm/admin/setting/url
> 
> 2) Install extension via CiviCRM's "Manage Extensions" page.

But i cannot see the Stripe Payment Processor in the list on the "Manage Extensions" page. Maybe my version of CiviCRM is too high? If so, can you update the line "For CiviCRM 4.4 & up:" to instead say something like "For CiviCRM 4.4 to 4.6:"?

**Comment by karanjilka** [comment]
I just tried with CiviCRM 4.7 it works. Can you check path in "Administer » System Settings » Directories" » "CiviCRM Extensions Directory" that path should be full server path to your extension directory. Another reason could be the directory or file permission issues.

**Comment by drastik** [comment]
@SunyataZero 
Created a new release, so hopefully you see `4.7.1` in the Manage Extensions soon.  
If you don't see it by end of day tomorrow, let me know.

**Comment by Gravdan** [comment]
You also need to update civicrm Resource url as well. For example,
   [civicrm.root}/http://localhost/sites/all/modules/civicrm/

Then you can go civicrm.setting.php to get the right url for civicrm_root and copy the link and paste it in the extension resource url or if you click on that question mark under administer >settings>resource urls page it will give you the exact url format.

Good Luck!

**Comment by SunyataZero** [comment]
HI and thank you for these responses, i have updated to the new version now which (inside the extensions system) is compatible with CiviCRM 4.7

This is what it looked like for the old version (dev-version downloaded here from github few days ago):
![image](https://cloud.githubusercontent.com/assets/10245688/20050810/abfaf196-a4cb-11e6-91f2-fb94b8d3288f.png)

And this is the new version:
![image](https://cloud.githubusercontent.com/assets/10245688/20050817/b7a5d380-a4cb-11e6-9f63-f84bce146109.png)

Thank you for creating this plugin, it will really help our organization which brings in small donations

Kind Regards,
Tord

**Comment by SunyataZero** [comment]
And yes, i can now see the extension under "Add new":

![image](https://cloud.githubusercontent.com/assets/10245688/20063695/77c39a58-a508-11e6-81d5-760b48eec084.png)

**Comment by drastik** [comment]
Awesome!  Let me know if you spot any issues when testing (open separate issue).

Thanks!
