### ISSUE TITLE
Release issues

### ISSUE THREAD

**Issue by laryn** [drastik/com.drastikbydesign.stripe#162]
I was prompted on a site (in the extensions manager page) to update to the 4.7 release and only afterwards I realized it was a 4.6 site. I have been trying to track down sporadic "Stripe.js token not found" errors on this site and then discovered I had the 4.7 version installed. 

First of all, does that sound like a reasonable explanation for those errors, in your guesstimation? And secondly, do we need a separate 4.6 release, and/or a flag somehow so that 4.6 users aren't prompted to update to the 4.7 release?

**Comment by drastik** [comment]
Odd, sorry that happened to you.
I put 4.6 in the compatibility marker for the `4.7.1` release because the commits had all seemed backwards-compatible.  I guess not! 

What prior version was working for you?  The `4.6-dev` branch?

**Comment by laryn** [comment]
Well, I'm not 100% certain that this is the issue but I've rolled back to 4.6-dev for now. The error was sporadic, so hard to test/replicate...

**Comment by laryn** [comment]
I talked with this org and we decided to upgrade to 4.7 rather than spend time trying to troubleshoot this. Sorry I don't have better info here.
