### ISSUE TITLE
Webhook failing

### ISSUE THREAD

**Issue by elishowk** [drastik/com.drastikbydesign.stripe#168]
Hi,

I noticed that anytime a payment is failing the webhook in my civicrm 4.7.14 + extension 4.7.1 install in production is also failing with the following returned response:

     <div class="crm-section crm-error-message">DB Error: syntax error</div>

A failing payment means that the stripe webhook JSON body contains:

    "type": "invoice.payment_failed"

The weird thing is that my server returns a 200 OK code.
Anyone has the same error ? Is it a known issue ?

Thanks

**Comment by tttp** [comment]
Hi,
Is this an error as seen in the stripe log?

otherwise, you can have a db error and still have the server returning a 200 ok http code, but indeed, seems it should be a 4xx one.

**Comment by elishowk** [comment]
Hi,

`DB Error: syntax error` is in CiviCrm response body, the DB syntax error come from the Civi side, or Stripe's ext side... Unfortunately, I'm unable to find an error trace for the moment...

**Comment by h-c-c** [comment]
This issue should be resolved in the latest 4.7-dev version.  We're not even using DB queries any more for case: invoice.payment_failed.   It's all API calls now when a payment fails, so any SQL syntax errors would be long gone.
