### ISSUE TITLE
$1000 donations come through as $1

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#18]
I had a donation come in for $1,000. I confirmed with the donor that they intended to donate $1,000, and CiviCRM recorded it as $1,000.  Unfortunately stripe received the payment as $1.00.  This has happened twice.

**Comment by DaveBagler** [comment]
The problem is here:
https://github.com/drastik/civicrm_stripe/blob/4.3-1.7/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php#L204-L205

Changed from:

``` php
// Stripe amount required in cents.
$amount = $params['amount'] * 100;
```

to

``` php
// Strip amount required in cents.
$amount = (int)preg_replace('/[^\d]/', '', strval($params['amount']));
```

The problem was the existing code was trying to multiply <code>1,000.00</code> by <code>100</code> which is trying to multiply a string by a number.  So it was returning <code>100</code>.

The new code rips out all non digits from the amount making <code>1,000.00</code> become <code>100000</code> so you also no longer need to multiply by 100.

**Comment by drastik** [comment]
Is this tested working?

**Comment by DaveBagler** [comment]
Yeah, I ran through a few donations and got accurate amounts.

**Comment by drastik** [comment]
Committed, thanks!
https://github.com/drastik/civicrm_stripe/commit/eed5958e215de9e3736ca388c765edcc881aa79f

**Comment by kcristiano** [comment]
Hi,

I just applied this latest code and I am getting the following results:

$100.00 donation in CiviCRM --> Stripe gets $1.00
$5.55 donation in CiviCRM --> Stripe gets $5.55
$100.01 donation in CiviCRM --> Stripe gets $100.01

It looks like we still need to multiple this amount by 100

**Comment by kcristiano** [comment]
I meant to add that once I added back 

```

$amount = $params['amount'] * 100; 

```

After the preg_replace to strip non numeric characters it worked on my site.

Full Block from line 204 of com.drastikbydesign.stripe\CRM\Core\Payment\Stripe.php 

```
// Stripe amount required in cents.
    $amount = (int)preg_replace('/[^\d]/', '', strval($params['amount']));
    // Stripe amount required in cents.
    $amount = $params['amount'] * 100;
```

**Comment by drastik** [comment]
Wouldn't your $5.55 donation hit Stripe as $555 then?

**Comment by kcristiano** [comment]
You are correct it would,  but the above code is stripping the zeros after the decimal point, so whole dollars come through incorrectly.

I am going to look at it again, but this type of regex seems to be beyond me.

**Comment by drastik** [comment]
his preg_replace is just saying: Replace anything that isn't a digit [0-9] with ''  (with nothing)

**Comment by drastik** [comment]
So if you are having that problem, it would seem that CiviCRM doesn't include both digits after the . if the hundredths place isn't there.

Dave, are you experiencing the same thing?  I can rewrite this if that is the case.

**Comment by DaveBagler** [comment]
No I'm not experience any issues with the regex.

My donations amounts are coming is as <code>#,###.##</code> so for a thousand that's <code>1,000.00</code> and for one hundred it's <code>100.00</code> and for ten it's <code>10.00</code>.

The regex strips all non-digits so the comma for the thousands separator and decimal point.  So it implicitly multiplies by 100 when it removes the <code>.</code>.

**Comment by DaveBagler** [comment]
I just tested with a <code>$25</code> donation and the amount the strip plugin received was <code>25.00</code>, the regex converted it to <code>2500</code> and the payment in stripe says <code>$25</code>.

**Comment by kcristiano** [comment]
Let me go through all my settings, on my site (CMS is WordPress) any zeros after the decimal are being stripped.

Perhaps they were never there at all.

**Comment by drastik** [comment]
@kcristiano 
Ahh, there's your problem:  Wordpress

:tongue: 

What CiviCRM version?

**Comment by kcristiano** [comment]
Civi is 4.4.2

**Comment by drastik** [comment]
Ok, I'm experiencing this on Civi 4.4.2.  Fix incoming.

**Comment by drastik** [comment]
Ok, committed.  Also fixed the BillingBlock.tpl issues.

It has also been updated in CiviCRM's repos so 4.4 users can download directly from "Manage Extensions" again.

https://github.com/drastik/civicrm_stripe/commit/18482c730fa02587c204a8c148960c392d6d1eca

**Comment by kcristiano** [comment]
Thanks.  The payments are going through as expected.  I am having issues with recurring memberships showing as Pending (Incomplete Transaction) in CiviCRM.  These look fine in Stripe.  I will look at the webhook later, and if I see an issue I will open another ticket.

**Comment by eileenmcnaughton** [comment]
The fix in 4.3.17 was not working for me - however, using the built in CiviCRM method did - see https://github.com/eileenmcnaughton/civicrm_stripe/commit/90eedb319e57d8dc2afca8e1c1c3150159f0e6b6

**Comment by eileenmcnaughton** [comment]
I've also added a ticket in JIRA http://issues.civicrm.org/jira/browse/CRM-14011

**Comment by drastik** [comment]
I don't think that will work.  That function has the possibility of adding a thousands separator.

``` php
    if ($config->monetaryThousandSeparator) {
      $mon_thousands_sep = $config->monetaryThousandSeparator;
    }
    else {
      $mon_thousands_sep = ',';
    }
```

The lines changed from 4.3 don't match the latest in 4.4.  I'll update it to that.

https://github.com/drastik/civicrm_stripe/commit/18482c730fa02587c204a8c148960c392d6d1eca#diff-8dcbf2bfe3fcb3899e049399543df444L205

**Comment by eileenmcnaughton** [comment]
I don't it adds it though - it removes it :       $value = str_replace($mon_thousands_sep, '', $value); & then it replaces the decimal separator with a decimal point
