### ISSUE TITLE
<div> on payment form causing extra white space

### ISSUE THREAD

**Issue by formeroosid** [drastik/com.drastikbydesign.stripe#182]
Hello,
Just started using the extension in Wordpress/Civicrm. I created a donation page and I'm not able to process payments. However, there is a <div> before the form itself that is causing a bunch of extra whitespace. This seems to happen regardless of the theme. How can I fix this? 

![div](https://cloud.githubusercontent.com/assets/5659343/22868341/c8a74c7a-f149-11e6-862c-9acc0d737d48.JPG)

Thanks for your help
Jamie

**Comment by h-c-c** [comment]
Yeah, for some reason the javascript is enclosed in paragraph tags.  Let me see...

**Comment by h-c-c** [comment]
It looks like some code you're running is going _crazy_ and dropping ```<p>``` tags all over your page.  I don't believe it's coming from the Stripe extension or even Civi.  Look at how there are ```<p>``` tags injected in the javascript!     

![screen shot 2017-02-12 at 9 15 55 pm](https://cloud.githubusercontent.com/assets/5252344/22868898/ccf9d03a-f168-11e6-8f00-b3466eb71a2a.png)

I would start by disabling all your Wordpress plugins (except Civi of course). Switch back to the default WP theme.  Add them back one at a time until you find the culprit.

**Comment by formeroosid** [comment]
Found it. It was one of those JS embedding plugins that I had installed 
months ago. I'll have to look for one that actually works. :-)

Thanks for the quick reply.

Jamie

------ Original Message ------

**Comment by h-c-c** [comment]
Sure thing!

**Comment by h-c-c** [comment]
Closing because of external cause: Wordpress plugin gone wild.
