### ISSUE TITLE
"DB Error: already exists" on payment submission

### ISSUE THREAD

**Issue by notnotnate** [drastik/com.drastikbydesign.stripe#193]
_com.drastikbydesign.stripe v4.7.1
civicrm-core v4.7.17_

Upon submitting a contribution payment through the CiviCRM UI, the following error is given:
    
    DB Error: already exists
<img width="419" alt="screenshot 2017-03-15 12 01 21" src="https://cloud.githubusercontent.com/assets/1762731/23963520/22bc7984-0977-11e7-9597-cc090aeb5efd.png">

The full log shows the following: 

    Fatal Error Details = 
    Array(

    [callback] => Array(
            [0] => CRM_Core_Error
            [1] => handle
        )
    [code] => -5
    [message] => DB Error: already exists
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_stripe_customers
          (email, id, is_live, processor_id) VALUES ('notnotnate@example.com', 'cus_AIGlSm4zmaQsGI', '1', 5) [nativecode=1062 ** Duplicate entry 'notnotnate@example.com' for key 'email']
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_stripe_customers
          (email, id, is_live, processor_id) VALUES ('notnotnate@example.com', 'cus_AIGlSm4zmaQsGI', '1', 5) [nativecode=1062 ** Duplicate entry 'notnotnate@example.com' for key 'email']
    [to_string] => [db_error: message="DB Error: already exists" code=-5 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_stripe_customers
          (email, id, is_live, processor_id) VALUES ('notnotnate@example.com', 'cus_AIGlSm4zmaQsGI', '1', 5) [nativecode=1062 ** Duplicate entry 'notnotnate@example.com' for key 'email']"]
    )

This issue seems to have developed after upgrading civiCRM-core to v4.7.17

Any ideas what might be happening?

**Comment by arborrow** [comment]
Take a look at your indexes on the civicrm_stripe_customers table. I ran into a similar issue after upgrading at https://github.com/drastik/com.drastikbydesign.stripe/issues/191 - essentially you want to remove the unique index on email and create a unique index on the id field.

**Comment by notnotnate** [comment]
Thanks @arborrow. Dropping the unique index on the email column and creating a new unique index on the id column solved this for me. 

Here is my query:

`ALTER TABLE civicrm_stripe_customers DROP INDEX email; CREATE UNIQUE INDEX id ON           civicrm_stripe_customers(id);`

I understand how this fixes the error message, but doesn't this just mean that instead of looking up the existing stripe customer and using that, now the extension is just creating new customers for each contribution? Seems like there is a reason there was a unique on the email, and this fix bypasses that.

**Comment by arborrow** [comment]
@notnotnate - as I understand it, the lookup is done based on the customer id rather than email address. Where this was an issue was when there was an existing test record (different id but same email). By dropping the unique email index, now there can be 2 entries for the same email address (one live and one one test). You should not see a bunch of new customers for each contribution.

**Comment by notnotnate** [comment]
Ah, that makes sense. I was thinking the ID was an auto increment value, not the stripe customer ID. With that in mind, your solution seems solid. Thanks again @arborrow

**Comment by h-c-c** [comment]
This is really #191.

**Comment by arborrow** [comment]
@notnotnate - as you can see from https://github.com/drastik/com.drastikbydesign.stripe/commit/5512c2dd7c20f9f20a03c616ddb8338a904fe761 you have simply done manually what is intended by the upgrader so you should be good to go
