### ISSUE TITLE
Received time always equals midnight for recurring donations

### ISSUE THREAD

**Issue by scardinius** [drastik/com.drastikbydesign.stripe#194]
Hi,

Could someone explain why contribution (child of recurring contribution) doesn't have time in datetime field `received_date`? 

When contribution is on the beginning (Pending) then receive_date has full date, with time. However after confirmation `receive_date` has only date.

It was intentional?

**Comment by h-c-c** [comment]
This is a CiviCRM issue...I made a patch for it which was merged and made it into ver 4.7.17.  https://github.com/civicrm/civicrm-core/pull/9680/commits/970aa2fedb71e05431a18bc0f215e9bcb47f3055

I have to look and see if I made a PR for 4.6...I don't think so.

**Comment by scardinius** [comment]
@h-c-c ok, thx for explanation!

**Comment by h-c-c** [comment]
You're welcome!
