### ISSUE TITLE
Monthly receipt emails for monthly donations?

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#197]
Since upgrading to the latest release, I seem to be getting some odd behaviour with the contribution receipts for recurring contributions.

For example, before upgrading when a visitor started a recurring donation, they would get an email receipt, but they wouldn't get an email receipt for each month.

After the upgrade, they seem to receive an email receipt every month.

**Comment by h-c-c** [comment]
Hey @DaveBagler, that's the default behavior.   I'm not quite sure when that started to be the case.  In any event, you can change this line if you prefer the old way:

https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/CRM/Stripe/Page/Webhook.php#L217

You would change it to be `'is_email_receipt' => 0,`

**Comment by DaveBagler** [comment]
Thanks so much!

**Comment by h-c-c** [comment]
You're very welcome!

**Comment by DaveBagler** [comment]
@h-c-c, it seems like this is happening again, even with the modification above.

**Comment by h-c-c** [comment]
@DaveBagler That is mysterious. At this point I would say it's an issue with CiviCRM's  contribution.repeattransaction API call.  It is supposed to respect this parameter `'is_email_receipt' => 0,` and not send the email receipt.

Are you up to date with your Civi version? 

I wonder if this is being overridden by the `is_email_receipt` field in the `civicrm_contribution_recur` table.  Unfortunately, it seems that can't be set in the GUI.  Maybe try setting one to `0` and see what happens.

**Comment by DaveBagler** [comment]
@h-c-c, you sure know your Civi.  That was exactly what it was, thank you!

**Comment by h-c-c** [comment]
Haha, thank you!  So this really solved it for you?

If so, I bet @eileenmcnaughton would be interested to know that repeattransaction behaves like this in 4.6.

**Comment by eileenmcnaughton** [comment]
hmm - that's the one you fixed in 4.7 isn't it - to take is_email_receipt = 0 - with a unit test I think

**Comment by h-c-c** [comment]
Nope, not me...could it be Alan?  
https://github.com/civicrm/civicrm-core/pull/9353/commits

**Comment by eileenmcnaughton** [comment]
Hmm - I'm pretty sure a test was added - I think that PR might have broken again later & then Agileware fixed & added a test
