### ISSUE TITLE
Webform test mode not working

### ISSUE THREAD

**Issue by TomCrawshaw** [drastik/com.drastikbydesign.stripe#198]
Stripe payments in test and live mode using a CiviCRM contribution page work correctly, but using a Webform configured to use the same CP , and set to use Test mode, does not, as Stripe replies with "a known test card number was used in live mode" (or words to that effect). I tried forcing the mode to "test" by editing line 283 in Stripe.php to set $stripe_ppid = the test payment processor, thus:

    var_dump($form->_paymentProcessor);
      return $stripe_ppid = 7 //$form->_paymentProcessor['id'];
    }

but although this appeared to work (Stripe responded correctly, test contribution listed in CiviCRM), attempts to view or edit the contribution in Civi cause an on screen error "Network Error
Unable to reach the server. Please refresh this page in your browser and try again." and in the log:

Apr 04 16:21:57  [info] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(34) "Expected one PriceSet but found 16"
  ["code"]=>
  NULL
  ["exception"]=>
  object(CiviCRM_API3_Exception)#393 (8) {
    ["extraParams":"CiviCRM_API3_Exception":private]=>
    array(4) {
      ["count"]=>
      int(16)
      ["is_error"]=>
      int(1)
      ["error_message"]=>
      string(34) "Expected one PriceSet but found 16"
      ["error_code"]=>
      string(9) "undefined"
etc.......
----------------------
The price set error may be because I'm forcing the test mode, so the 1st issue is why isn't test mode working in webforms? The CP does not use a price set either..

I'm using Stripe ext 4.7 dev-4, CiviCRM 4.7.15 on Drupal 7.52.

Tom Crawshaw

**Comment by h-c-c** [comment]
Hey @TomCrawshaw, I'm well aware. But this is not our issue, it's a CiviCRM webforms problem.  You might consider opening a JIRA.  

But there is a simple workaround, just add another Stripe pay processor and call it something like "stripe-testing".  Then put your test api keys in the live fields and do your webforms testing using this payproc.
