### ISSUE TITLE
Losing the session

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#200]
After upgrading to the latest commit on the 4.7-dev branch I am running into this error when making a donation:
<img width="1680" alt="screen shot 2017-04-06 at 10 51 02 am" src="https://cloud.githubusercontent.com/assets/3266985/24760562/0b0a13ae-1ab7-11e7-9d89-bd6b5f567f77.png">

I ran into this issue before and it was losing the session ID: https://github.com/drastik/com.drastikbydesign.stripe/issues/125

**Comment by DaveBagler** [comment]
If I'm logged in as an admin, rather than getting the error I get sent to /civicrm/admin/setting/localization?reset=1 with this warning:
<img width="420" alt="screen shot 2017-04-06 at 10 58 20 am" src="https://cloud.githubusercontent.com/assets/3266985/24760952/13d80d50-1ab8-11e7-9abf-e5e234a6e2a0.png">

**Comment by h-c-c** [comment]
Ok, before you upgraded, were you still using the mish-mash version to get by?  If that's the case, I'd say #125 was never resolved.  

Could you post your localization settings?  

For good measure, can you look at your `'CIVICRM_UF_BASEURL'` in civicrm.settings.php to make sure it's what you expect.  

Does your naked domain redirect to a www (or other) subdomain? 

Do you have any other rewrite rules in place, like redirecting http to https?

**Comment by DaveBagler** [comment]
Here are my localisation settings:
<img width="748" alt="screen shot 2017-04-06 at 11 35 30 am" src="https://cloud.githubusercontent.com/assets/3266985/24762735/3c17f38e-1abd-11e7-92d5-a3263b66c687.png">
<img width="1665" alt="screen shot 2017-04-06 at 11 35 47 am" src="https://cloud.githubusercontent.com/assets/3266985/24762736/3c445758-1abd-11e7-8462-b60284b804c3.png">

My `CIVICRM_UF_BASEURL` is `https://evidencefordemocracy.ca/` which is what I expect.

I rewrite www to non-www and I rewrite http to https.

**Comment by h-c-c** [comment]
Thanks, this will help towards trying to reproduce the issue.  

Have you tried not inheriting the default language from your CMS and setting it within CiviCRM?  

Is your Drupal site multi-language?

Which Civi / Drupal versions are you running?

I'd be curious what version of the Stripe extension _was_ working for you.  If it's a frankenstein version, I think you can send it to me on Mattermost (peter).

**Comment by DaveBagler** [comment]
Nope

**Comment by h-c-c** [comment]
Sorry, can you look at the updated previous post?

**Comment by DaveBagler** [comment]
I think what happened is that the upgrades to the schema say they've been run but I think I'm basically on the 1.9 or whatever schema.  Could you send me what the tables should look like?  If you don't have time don't worry I can make a clean install.

**Comment by DaveBagler** [comment]
It's just the three tables right?

**Comment by h-c-c** [comment]
Yeah, but I don't think this has anything to do with it, as this is the same issue from before.   It would not have anything to do with the most recent schema changes.

That said, you can confirm it went well, by looking for the subscription_id column in civicrm_stripe_subscriptions.  It should be populated.

Get back to me with the info I requested when you get chance, ok?  I wasn't clear what the "Nope" was in reference to.

**Comment by DaveBagler** [comment]
Sadly, my subscription_id is null for every record in civicrm_stripe_subscriptions.

In theory, I could backup those three tables. Uninstall the plugin, reinstall the plugin, and restore the data from the backup to get fully onto the current version?

**Comment by DaveBagler** [comment]
**Have you tried not inheriting the default language from your CMS and setting it within CiviCRM?**
I'm going to have to try this.

**Is your Drupal site multi-language?** It is. (English and French)

**Which Civi / Drupal versions are you running?** latest stable of Drupal 7 and latest stable 4.6 Civi

**I'd be curious what version of the Stripe extension was working for you. If it's a frankenstein version, I think you can send it to me on Mattermost (peter).**
Yeah me too, I can't remember exactly what it was.

**Comment by h-c-c** [comment]
> Sadly, my subscription_id is null for every record in civicrm_stripe_subscriptions.

Ok, so did you get errors when you ran the db upgrades from your extensions admin page?   If so, did you note what they were?

>In theory, I could backup those three tables. Uninstall the plugin, reinstall the plugin, and restore the data from the backup to get fully onto the current version?

No, that's not a good course of action.  The data and schema come together. Anything you hope to gain from a fresh install would be overwritten with you import the tables.     

If anything, I could walk you through a manual db upgrade. 

> Is your Drupal site multi-language? It is. (English and French)

Hmm...it could be possible that you may _have_ to run a multi-language civi site.   From your localization settings, it seems you're not currently doing that.

**Comment by DaveBagler** [comment]
I didn't see any errors in the UX, might have just missed them. I'm currently almost finished a manual upgrade (using https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/CRM/Stripe/Upgrader.php and a fresh install as a guide.)

**Comment by DaveBagler** [comment]
OK, I've manually updated my DB but still get the same issue.  The error message comes up when clicking the confirm contribution amount, not the final submit contribution form.

**Comment by DaveBagler** [comment]
@h-c-c, I found the cause of the issue, the error message is a red herring it doesn't seem like it's even related to #125.

Given the back in forth in this issue.  I'm going to close this issue and open a new one.
