### ISSUE TITLE
Some notices and errors in logs

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#210]
Drupal 7.5.4
CiviCRM 4.7.18
Stripe 4.7.2
PHP 5.6

Just an FYI that in my logs I am seeing various occurrences of: 

PHP Fatal error:  Cannot access protected property CRM_Event_Form_Participant::$_paymentProcessors in /home3/ignatia1/public_html/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe/CRM/Core/Form/Stripe.php on line 13

Stripe Notice: Undefined property of Stripe\Transfer instance: customer

Stripe Notice: Undefined property of Stripe\Customer instance: customer

and single instance of: 

PHP Notice:  Undefined index: CRM_Upgrade in /home3/ignatia1/public_html/sites/all/modules/civicrm/CRM/Queue/Service.php on line 131

PHP Strict Standards:  call_user_func_array() expects parameter 1 to be a valid callback, non-static method CRM_Upgrade_Incremental_php_FourSeven::updateKenyanProvinces() should not be called statically in /home3/ignatia1/public_html/sites/all/modules/civicrm/CRM/Queue/Task.php on line 88

**Comment by jmcclelland** [comment]
See #218 - for work on the first error you are seeing.
