### ISSUE TITLE
Stripe must be default payprocessor to function

### ISSUE THREAD

**Issue by h-c-c** [drastik/com.drastikbydesign.stripe#217]
.....If it's not, you get the "Error: Stripe.js token was not passed!" message and can't process transactions.  This could easily be play a role in any issue that references the above error message, eg #76, #179 and possibly #89.

CiviCRM has ways of "un-defaulting" your payprocessor decision, so it may not be obvious that the issue title is 100% accurate.  For instance if you select Stripe (or any payprocessor) as your default, but don't check any accepted credit cards (visa/MC,AMEX,Discover), it has the same effect as _not_ choosing Stripe as the default (totally reasonable!).  Also, if you use a priceset with no default option, (as of May 25,'17), your default payprocessor choice will not be respected. (much less reasonable) 

The reason is, we were failing to dynamically add the stripe-payment-form class with javascript. Not for long!  :-)

**Comment by arborrow** [comment]
@h-c-c would you like me to test any scenario and verify that the patch fixes the issue? Let me know if there is anything I can do to be helpful.

**Comment by h-c-c** [comment]
I did on this end...works for me.  Go ahead, that would be awesome if you'd test it!

**Comment by arborrow** [comment]
I just commented on the commit that I tested it as well and it seems to work just fine, great work! Thanks for tracking down the issue and coming up with a fix.

**Comment by h-c-c** [comment]
Thank you, and thanks for testing @arborrow!
