### ISSUE TITLE
Stripe.js token was not passed! Report this message to the site administrator. (on civicrm 4.7.20)

### ISSUE THREAD

**Issue by Moranne** [drastik/com.drastikbydesign.stripe#226]
(I have submitted this problem on the stack-exchange : https://civicrm.stackexchange.com/questions/19307/urgent-stripe-js-token-was-not-passed-report-this-message-to-the-site-adminis)

I recently upgraded civicrm from 4.7.16 to 4.7.20 (on Drupal 7.56).

Now, when I use a Contribtion Page to make a payment, I get the following message : "Stripe.js token was not passed! Report this message to the site administrator." (tested on different existing Contribution Pages with same result).

I already had this same message in the past, for webform embedded payments (see https://civicrm.stackexchange.com/questions/16210/stripe-js-token-was-not-passed-using-webform-integration), but it was solved by a fix (https://github.com/drastik/com.drastikbydesign.stripe/pull/159/files).

But this time, the problem happens on simple Contribution Pages (which previously worked).

To be complete, since this upgrade, I have had an other problem on webform embedded payments (submitted here : https://civicrm.stackexchange.com/questions/19293/stripe-extension-fails-with-a-new-account-civi-4-7-20) :

- old webforms continue to work properly (I don't have this stripe.js message and the payments succeed) (but for how long ?)
- new webforms based upon new stripe Accounts send the payment to an other (existing) account.

May be both problems are linked ?

**Comment by h-c-c** [comment]
You wrote in the stackexchange post that you're using 4.7.1.  Please upgrade to the current 4.7-dev github version.

**Comment by Moranne** [comment]
Super ! Thank you
