### ISSUE TITLE
avoid intrusion detection system

### ISSUE THREAD

**Issue by jmcclelland** [drastik/com.drastikbydesign.stripe#228]
CiviCRM has an intrusion detection system that seems to sometimes overly aggressively stop anonymous requests in their track.

I've noticed it with some webhooks - so adding an excpetion using the [idsException](https://docs.civicrm.org/dev/en/master/hooks/hook_civicrm_idsException/) hook seems like the way to go.

**Comment by mattwire** [comment]
@jmcclelland Can this issue be closed as PR has now been merged?

**Comment by jmcclelland** [comment]
Yes!
