### ISSUE TITLE
New release, please?

### ISSUE THREAD

**Issue by JoeMurray** [drastik/com.drastikbydesign.stripe#230]
Now that https://github.com/drastik/com.drastikbydesign.stripe/pull/227 has been merged, I think it is necessary to create a new release before the core team will receive any funds, since the code has to be deployed to the hundreds of sites using the extension. Would you be willing to create a new release so it can be auto-deployed from within CiviCRM instances? Thanks!

**Comment by h-c-c** [comment]
Yes, sorry a new release is way over due.  I had a couple of PRs I wanted to test and some features to document before doing so.   Realistically, this might take few weeks.  Do think that's reasonable?

Thanks

**Comment by JoeMurray** [comment]
Hi Peter,
Just checking if you have managed to release a new version? It's only then
that upgrades will occur and money will start accruing to CiviCRM LLC.
Every day that goes by means less to them, if this hasn't been released.

Joe Murray, PhD
President, JMA Consulting
joe.murray@jmaconsulting.biz
skype JosephPMurray twitter JoeMurray
416.466.1281

**Comment by h-c-c** [comment]
Ok, let's just roll with it then. Sorry for the holdup!

**Comment by JoeMurray** [comment]
Great, thanks!

Joe Murray, PhD
President, JMA Consulting
joe.murray@jmaconsulting.biz
skype JosephPMurray twitter JoeMurray
416.466.1281

**Comment by JoeMurray** [comment]
Hi @h-c-c and @drastik .
Would you be able to tag a new release including the PR from @monishdeb so CiviCRM LLC can start to benefit from the money being processed by your extension? If you want we could submit a PR with the relevant changes to info.xml.

**Comment by mattwire** [comment]
@JoeMurray It's in 4.7.2 that was released on 7 Sep!

**Comment by JoeMurray** [comment]
Ah, thanks @mattwire . 
I thought so at first, then Mathieu (bgm, mlufty) indicated it wasn't due to the release date on 4.7.2 being 2016. 

But that's the date for 4.7.1, the update of which just got missed during the tagging and release of 4.7.2. 

I've submitted a PR https://github.com/drastik/com.drastikbydesign.stripe/pull/243 that would update version to 4.7.3 with today's date. It would need to be merged and have a person with repo write permissions then create a 4.7.3 tag (though that would pick up any other changes from Sep 7 till Oct 25).

**Comment by h-c-c** [comment]
@JoeMurray let me know if you're set?  Thanks

**Comment by mattwire** [comment]
@JoeMurray As this has been done, can you close this issue please?
