### ISSUE TITLE
Require CC info even though event with discount is $0

### ISSUE THREAD

**Issue by vermontdevil** [drastik/com.drastikbydesign.stripe#254]
Hi - I'm seeing this issue where the stripe extension is requiring fields to be entered even though the cost is $0 due to a 100% discount. 

The Stripe CC block remains hidden as well.

Any insight?

Thanks

**Comment by h-c-c** [comment]
@vermontdevil what Civi version are you using?

**Comment by vermontdevil** [comment]
Hi - 4.6. I'm working to update it to 4.7 in a few months (after a major event is done). Could this be the reason?

**Comment by h-c-c** [comment]
Great, can you just uncomment line 160 of js/civicrm_stripe.js ?

https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/js/civicrm_stripe.js#L160

We use 4.6 and thankfully it seems the section of code is no longer getting hit when going back.

**Comment by vermontdevil** [comment]
That works! Thanks!
