### ISSUE TITLE
`civicrm_stripe_subscriptions`.`processor_id` seems backwards

### ISSUE THREAD

**Issue by jamezpolley** [drastik/com.drastikbydesign.stripe#257]
I'm not sure if this is a bug with this extension or if it's a broader civicrm issue, so I'm starting here and I'll file it elsewhere if needed.

`civicrm_payment_processor` has:

id | is_test | username 
--|-------|-----------
3 | 0 | sk_live_.....
4 | 1 | sk_test_.....

so processor 4 is the stripe test processor; processor 3 is the stripe live processor.

However, `civicrm_stripe_customers` has:

email | is_live | processor_id
------|-----|-------------
email@domain.com | 1 | 3
email@domain.com | 0 | 4

ie, the *live* transactions are being recorded against the *test* processor,with with is_live set to 1; while test transactions are being recorded against the live processor with is_live set to 0.

This seems backwards to me. Am I missing something?

**Comment by h-c-c** [comment]
It's not backwards. It's just that is_live is the opposite of is_test.   Look at it again and it will make sense.   Stripe's attribute is livemode.  Civi's is is_test.  This is how we reconcile them.

Are you having an issue relating to a actual transaction or just poking around?

**Comment by h-c-c** [comment]
I'd encourage you to look at the source code if you're interested in learning more about the extension.   If you grep for `test` or `live`, you would have probably come across this:

https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/CRM/Stripe/Page/Webhook.php#L87

**Comment by jamezpolley** [comment]
Yeah, this makes perfect sense to me now. I don't know why I thought it was backwards at the time.

Thanks for the response :)
