### ISSUE TITLE
Support for additional Stripe Payment options (Sofort, SEPA DD, Sofort+Sepa DD, Giropay)

### ISSUE THREAD

**Issue by mp21-org** [drastik/com.drastikbydesign.stripe#261]
Hello once more,

as a US-based non profit we would also like to give european donors the possibility to donate with their favorite methods of payment. Stripe supports several of these payment methods that we would like to integrate with this plugin.

Of special intrest is the combination of Sofort + Sepa Direct Debit. Basically allowing recurring donations while verifying the bank account on the first donation via Sofort.

This request is probably a very complex one and could lead to substantial changes to this plugin. The non-profit that I work for is thinking about dedicating some our tech-intern hours/days to this topic. It would be great to get some input from the community how these features should look like. :-)

**Comment by psampont** [comment]
Duplicate with issue #186
