### ISSUE TITLE
Error relating this subscription id [...] to the one in civicrm_stripe_subscriptions

### ISSUE THREAD

**Issue by michaelmcandrew** [drastik/com.drastikbydesign.stripe#265]
We've been running Stripe with a client since 4th September. In this time, they have processed 220 payments but 19 of them have not ended up in CiviCRM.

Looking at one of these missing payments, I can see that Stripe has tried to deliver the payload 7 times over a period of about three days. Each time I get a backtrace along the lines of

#0 .../sites/all/modules/civicrm/CRM/Core/Error.php(381): CRM_Core_Error::backtrace("backTrace", TRUE)                                                                                       
#1 .../sites/all/civicrm_extensions/com.drastikbydesign.stripe/CRM/Stripe/Page/Webhook.php(30): CRM_Core_Error::fatal("Error relating this subscription id (sub_Dn3Mp59bjvUu0O) to the one in civicr...") 
#2 .../sites/all/civicrm_extensions/com.drastikbydesign.stripe/CRM/Stripe/Page/Webhook.php(154): getRecurInfo("sub_Dn3Mp59bjvUu0O", 0)                                                                    
#3 .../sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Stripe_Page_Webhook->run((Array:3), NULL)                                                                                                  
#4 .../sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:13))                                                                                                            
#5 .../sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))                                                                                                             
#6 .../sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))                                                                                                           
#7 .../includes/menu.inc(527): civicrm_invoke("stripe", "webhook")                                                                                                                                        
#8 .../index.php(21): menu_execute_active_handler()                                                                                                                                                       
#9 {main} 

Indeed the subscription is not there. 

And looking in CiviCRM I do not see any contact details for these payments (based on the email address contained in Stripe) or any contacts created at that time.

So it seems as if the contact is never created in CiviCRM.

Any ideas on what might be going on here, or how I can debug?

PS we are running on 5.0.beta2.

**Comment by michaelmcandrew** [comment]
Looking in CRM_Stripe_Page_Webhook, it appears to be looking for the subscription id in civicrm_stripe_subscriptions. I can confirm that the subscrtiption ID doesn't exist there.

**Comment by mattwire** [comment]
Hi @michaelmcandrew Could you please raise this as an issue here: https://lab.civicrm.org/extensions/stripe/issues

**Comment by michaelmcandrew** [comment]
done https://lab.civicrm.org/extensions/stripe/issues/17
