### ISSUE TITLE
Post 6.0 - Unable to add contribution

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#270]
When attempting to add a contribution from:
civicrm/contact/view/contribution?reset=1&action=add&cid=63&context=contribution&mode=live
After filling in the information on the form and saving the contribution I receive an error message:

Unable to complete payment! Missing paymentIntentID.

This also happens on our donation page: 
https://ignatianinstitute.org/civicrm/contribute/transact?reset=1&id=1 

Any suggestions on what might be happening and what I can do to resolve it? 

Peace - Anthony

Environment:
Drupal 7
CiviCRM 5.17.4
Stripe Payment Processor (com.drastikbydesign.stripe) version 6.1.4
MJWShared (mjwshared) version 0.4.3
API v4 (org.civicrm.api4) version 4.4.3
PHP version 7.2.22

**Comment by arborrow** [comment]
I also applied the pull request at:
https://github.com/civicrm/civicrm-core/pull/15340

To be clear, I tried both without and with the patch and was hitting same error message about the missing paymentIntentID

**Comment by drastik** [comment]
Wrong project I think?  Core & another organization took over the Stripe plugin and it should have a different project namespace.

**Comment by arborrow** [comment]
Oops, you are correct - I have posted the comments to an existing, similar issue at https://lab.civicrm.org/extensions/stripe/issues/97

p.s. - I think I still owe you a beer sometime ;) Thanks for all your work over the years with this extension.
