### ISSUE TITLE
Pass CiviCRM locale to Stripe

### ISSUE THREAD

**Issue by jensschuppe** [drastik/com.drastikbydesign.stripe#271]
Stripe uses its `auto` mode for detecting the UI language by identifying the browser language, but is capable of receiving a specific locale during initialization (See [docs](https://stripe.com/docs/js/initializing#init_stripe_js-options-locale)).

Is this already implemented in some way or, if not, can someone give me a starting point for a PR?

**Comment by mattwire** [comment]
@jensschuppe This is the old repository and is unmaintained - please report via https://lab.civicrm.org/extensions/stripe

**Comment by jensschuppe** [comment]
Sorry for that!
