### ISSUE TITLE
Unable to create Submit Credit Card Contribution

### ISSUE THREAD

**Issue by arborrow** [drastik/com.drastikbydesign.stripe#28]
The following issue was reported to me and it sounds similar to the post at http://drastikbydesign.com/blog-entry/civicrm-stripe-payment-processor Submitted by Joe (not verified) on Thu, 2013-07-18 03:48

When a person calls to make a contribution, [or say pay their tuition] via credit card, I go in to civicrm record their payment. When I submit the payment an error page comes up that reads:

Sorry but we are not able to provide this at the moment.

Stripe.js token was not passed! Have you turned on the CiviCRM-Stripe CMS module?

Return to home page.

Here is the url of such a page.

https://ignatianinstitute.org/civicrm/contact/view/contribution  

We are running  CiviCRM 4.4.3, Drupal 7.24, Stripe extension 1.7 and version 1.9.0 of stripe-php.

What might be preventing the token from being passed? I want to verify with the user that they are first selecting the contact and then going to that contact's contribution page and clicking on Submit Credit Card Contribution. 

I am working to get more detailed information from the user, but my understanding is that the module https://drupal.org/project/civicrm_stripe (7.x-1.0 installed but not enabled on the site in question) was not required for CiviCRM 4.4.x

I find the question about the module confusing. Is it a suggestion to turn it on so that the token gets passed or a possible cause of the error. Perhaps that error message could be clarified a bit so it is clear what the desired state of that module is.

From what I can tell by looking at the code the stripe_civicrm_buildForm function is supposed to create the element and the drupal module is no longer needed. It does not appear that the processor type is being passed along.   Doing a var_dump of $params I did not see stripe_token listed. Going back further I did not see that Stripe is listed as the payment processor type and thus the element does not appear to be created. 

I can email you the var_dump of $params or anything else to help troubleshoot why we do not seem to be able to add a credit card (Stripe) contribution. Thanks for your help resolving this issue.

Peace - Anthony

**Comment by arborrow** [comment]
From - https://www.ignatianinstitute.org/civicrm/contact/view/contribution?reset=1&action=add&cid=65&context=contribution&mode=live 

// Use Stripe.js instead of raw card details.
    if (isset($params['stripe_token'])) {
      $card_details = $params['stripe_token'];
    }
    else {
      CRM_Core_Error::fatal(ts('Stripe.js token was not passed!
        Have you turned on the CiviCRM-Stripe CMS module?'));
    }

I added a var_dump of $params after I fill out the form and hit save. I see no reference to the token in the form. Here in what I have (x'ing out the sensitive data):

$params: array(78) 
{ 
["hidden_custom"]=> string(1) "1" 
["hidden_custom_group_count"]=> array(1) 
{ 
[""]=> int(1) } 
["qfKey"]=> string(37) "1709f671cad05fbc0bf4014b8d5163c3_6322" 
["entryURL"]=> string(136) "https://ignatianinstitute.org/civicrm/contact/view/contribution?reset=1&action=add&cid=65&context=contribution&mode=live" 
["hidden_CreditCard"]=> string(1) "1" 
["billing_first_name"]=> string(7) "Anthony" 
["billing_middle_name"]=> string(1) "R" 
["billing_last_name"]=> string(6) "Borrow" 
["billing_street_address-5"]=> string(20) "619 Copper Avenue NW" 
["billing_city-5"]=> string(11) "Albuquerque" 
["billing_state_province_id-5"]=> string(4) "1030" 
["billing_postal_code-5"]=> string(5) "87102" 
["billing_country_id-5"]=> string(4) "1228" 
["credit_card_number"]=> string(16) "6011xxxxxxxxxxxx" 
["cvv2"]=> string(3) "xxx" 
["credit_card_exp_date"]=> array(2) 
{ 
["M"]=> string(1) "x" 
["Y"]=> string(4) "xxxx" } 
["credit_card_type"]=> string(8) "Discover" 
["hidden_AdditionalDetail"]=> string(1) "1" 
["hidden_Honoree"]=> string(1) "1" 
["honor_type_id"]=> string(0) "" 
["frequency_interval"]=> string(0) "" 
["frequency_unit"]=> string(3) "day" 
["installments"]=> string(0) "" 
["financial_type_id"]=> string(1) "1" 
["is_email_receipt"]=> int(1) 
["from_email_address"]=> string(32) "ISI " 
["receive_date"]=> string(14) "20140114104600" 
["receive_date_time"]=> string(7) "10:46AM" 
["receipt_date"]=> string(14) "20140114104616" 
["receipt_date_time"]=> string(0) "" 
["payment_processor_id"]=> string(1) "3" 
["total_amount"]=> int(25) 
["currency"]=> string(3) "USD" 
["source"]=> string(0) "" 
["soft_credit_contact"]=> array(5) 
{ 
[1]=> string(0) "" 
[2]=> string(0) "" 
[3]=> string(0) "" 
[4]=> string(0) "" 
[5]=> string(0) "" } 
["soft_credit_contact_select_id"]=> array(6) 
{ 
[1]=> string(0) "" 
[2]=> string(0) "" 
[3]=> string(0) "" 
[4]=> string(0) "" 
[5]=> string(0) "" 
[6]=> string(0) "" } 
["soft_credit_profiles"]=> array(5) 
{ 
[1]=> string(0) "" 
[2]=> string(0) "" 
[3]=> string(0) "" 
[4]=> string(0) "" 
[5]=> string(0) "" } 
["soft_credit_amount"]=> array(5) 
{ 
[1]=> string(0) "" 
[2]=> string(0) "" 
[3]=> string(0) "" 
[4]=> string(0) "" 
[5]=> string(0) "" } 
["MAX_FILE_SIZE"]=> string(8) "10485760" 
["price_1"]=> array(1) 
{ 
[1]=> int(1) } 
["amount_level"]=> int(0) 
["amount"]=> int(25) 
["payment_processor"]=> string(1) "3" 
["billing_state_province-5"]=> string(2) "NM" 
["state_province-5"]=> string(2) "NM" 
["billing_country-5"]=> string(2) "US" 
["country-5"]=> string(2) "US" 
["year"]=> string(4) "2018" 
["month"]=> string(1) "5" 
["ip_address"]=> string(13) "75.161.16.208" 
["currencyID"]=> string(3) "USD" 
["payment_action"]=> string(4) "Sale" 
["pcp_display_in_roll"]=> NULL 
["pcp_roll_nickname"]=> NULL 
["pcp_personal_note"]=> NULL 
["non_deductible_amount"]=> NULL 
["fee_amount"]=> NULL 
["net_amount"]=> NULL 
["trxn_id"]=> NULL 
["invoice_id"]=> NULL 
["campaign_id"]=> NULL 
["contribution_page_id"]=> NULL 
["thankyou_date"]=> string(4) "null" 
["honor_contact_id"]=> string(4) "null" 
["custom"]=> array(0) 
{ } 
["invoiceID"]=> string(32) "a5720ac641c5e02fc88d4f168b470276" 
["contactID"]=> string(2) "65" 
["first_name"]=> string(7) "Anthony" 
["middle_name"]=> string(1) "R" 
["last_name"]=> string(6) "Borrow" 
["street_address"]=> string(20) "619 Copper Avenue NW" 
["city"]=> string(11) "Albuquerque" 
["state_province"]=> string(2) "NM" 
["postal_code"]=> string(5) "87102" 
["country"]=> string(2) "US" 
["contributionType_name"]=> string(8) "Donation" 
["contributionPageID"]=> NULL 
["email"]=> string(20) "arborrow@jesuits.net" }

**Comment by drastik** [comment]
Ok, so this is as an administrative-type user manually adding a contribution in the backend, not a visitor using a donation page right?

**Comment by arborrow** [comment]
Correct

**Comment by arborrow** [comment]
I believe things work just fine when someone registers for an event and makes a payment - just having problems when the admin is trying to add a payment.

**Comment by drastik** [comment]
So, need to be sure this hook is adding stripe_token to that form:
https://github.com/drastik/civicrm_stripe/blob/4.4-1.8/stripe.php#L106

And figure out which .tpl is being used for that page for the JS magic.  Typically BillingBlock.tpl handles all the Stripe js, but I don't think it's involved on that page.

The alternative would be if we allowed the non-js method for Stripe on admin pages.

**Comment by drastik** [comment]
Or if anyone knows a creative way to not use .tpl's at all, if Civi extensions have matured to the point where we could inject JS on payment pages.

**Comment by arborrow** [comment]
Might sites/all/modules/civicrm/templates/CRM/Contribute/Form/Contribution.tpl provide some ideas of where you might inject something? That seems to be the tpl generating the page. Peace - Anthony

**Comment by drastik** [comment]
I think we have a winner.  Now we can do this with Namespace settings registry, similar to drupal_add_js setting.
Problem is, it was _just_ added, so may only work w/ Civi 4.4+.  Will try to find out more.

http://wiki.civicrm.org/confluence/display/CRMDOC/Resource+Reference

**Comment by drastik** [comment]
Update to latest here on GitHub and let me know if that fixes it.

I did away w/ BillingBlock.tpl entirely and made it all JS added by buildForm hook.
It now handles that backend "Record Contribution" page. (for me at least)

**Comment by arborrow** [comment]
I am testing the latest changes now, Does info.xml need to be updated in the 4.4-1.8 branch? It seems to still be pointing to 1.7. Also, in the README you state:

Version 1.8+ of this extension _must_ use Stripe's latest API verison as of Jan 9th, 2014.

When I go to Stripe.com I am showing  2013-12-03 (latest) as the latest API is that the one you are referencing or is there a more updated API?

**Comment by arborrow** [comment]
Good news, I successfully managed to add a contribution as admin on behalf of a user! That said, I did receive a network error:

Error: An unexpected error has occurred submitting your credit card to our secure credit card processor. This may be due to network connectivity issues, so you should try again (you won't be charged twice). If this problem persists, please let us know!

This happened with an actual transaction and a test transaction. I am having a strange issue getting https to work properly on the site so I could imagine it being related to that. The message goes away and then a notification appears letting me know the transaction was successful. 

I think we can close this issue as resolved. Many thanks for your heroic efforts today to make a pretty major change. 

Peace - Anthony

**Comment by arborrow** [comment]
Update: I resolved my htaccess issue and ensured everything was being handled consistently over https and I still receive the notification about an unexpected error before thing go through successfully.

**Comment by arborrow** [comment]
I am guessing that the error is a response from the Stripe server so I will follow up with them if it continues. Peace - Anthony

**Comment by drastik** [comment]
About the API version:  I meant "Whatever the latest was as of this date". 

I will re-word that in the README.  So yes, you should be fine if Stripe says it's the latest.

**Comment by drastik** [comment]
It's mainly for their update that took some charge response info out of the Charge object and introduced the new Balance transaction object.

**Comment by arborrow** [comment]
Sounds good, I suspected that was what you meant and figured it would be good to document that 1.8+ requires an API date of 2013-12-03, the current latest, or later when a newer one comes out. Peace -Anthony

**Comment by arborrow** [comment]
I am going to go ahead and close this issue as I believe the coding changes have fixed the issue that I was experiencing. Peace - Anthony
