### ISSUE TITLE
Can't process a credit card transaction on Wordpress 3.8, civicrm 4.4

### ISSUE THREAD

**Issue by awkale** [drastik/com.drastikbydesign.stripe#29]
I recently updated CiviCRM to 4.4 and I can't get stripe to work. It was working before this update. Anyone else have this issue and able to resolve it?

**Comment by arborrow** [comment]
Does you issue sound like mine at https://github.com/drastik/civicrm_stripe/issues/28 ?

We seem to be doing OK taking payments when folks register for an event but not going to a contact and submitting a credit card contribution. Is this where you are having trouble too?

Peace - Anthony

**Comment by awkale** [comment]
@arborrow no, it's not even processing the payment. There isn't even an error message after submitting the form.

**Comment by drastik** [comment]
Can you turn on some debugging and provide more info?  Give it a whirl if you find anything.  Pull requests are greatly appreciated. 

There are so many new problems being reported in 4.4.

**Comment by laryn** [comment]
I could be wrong, but #27, #28 and this one all seem to have some commonalities. Perhaps there is some solution that cracks them all at the same time. (Fingers crossed but don't have a pull request to contribute or even a good idea yet).

**Comment by awkale** [comment]
v 1.7 is working but v 1.8 is not. I can't figure out the changes to make it work.

**Comment by drastik** [comment]
Give it a shot w/ latest update.  Civi core changed the singleton/constructor for payprocs.
https://github.com/drastik/civicrm_stripe/commit/021e9a6d89b11b553965838f4eae1c05b6a65e87

**Comment by drastik** [comment]
Closing these old issues.

Please open / update if there is an issue using the latest (4.5-dev) version  (yes even if your CiviCRM is 4.4.x)
