### ISSUE TITLE
CiviCRM v4.3 has changes the id of exp_year / exp_month

### ISSUE THREAD

**Issue by dlobo** [drastik/com.drastikbydesign.stripe#3]
it is now:
# credit_card_exp_date_M
# credit_card_exp_date_Y

I did a quick test of this on 4.3 on WordPress and after fixing the above, things worked great (at least one test transaction went thru)

Posting the issue here, since the comment thread on the blog is a bit long

the place where i got stuck was i flipped the test and live keys (since stripe display it in a different order than civi) and it took me some time to figure that out. Noting that as a comment since it might help some other idiot like myself :)

**Comment by drastik** [comment]
Nice, thanks for the heads up lobo  :)

**Comment by ghost** [comment]
Joshua, I'm stuck on the exp_year is invalid error.  I have got 1.5 in service without it fixing that.  Is there another track for me to take ?  This site is live, and when a user clicks on Credit card payment, then switches to pay by cheque, the exp_year parameter should be an integer (instead is undefined) error comes up. If they refresh the form, no problems, but I can't tell that to my customer.  I'll be in touch tomorrow (Monday) on irc.

**Comment by drastik** [comment]
Yes, I haven't updated for Civi 4.3 yet.  Those changes will be rolled into v 1.5 once it's pushed to Civi's Extensions repo.

I'm also going to restructure the branches here on github, more like Drupal's style. 4.1-1.1,   4.2-1.5,  etc.

**Comment by drastik** [comment]
*Rather, what I mean is actually utilize that format, knocking 4.1 & source out of 4.2, etc.

**Comment by ghost** [comment]
Hi Joshua,

I realized that you're talking about 4.3 and I am talking 4.2. I have filed a separate issue report on github for you.

Erik

**Comment by drastik** [comment]
Fixed pay later & 4.3 compatibility.
http://civicrm.org/extensions/stripe-payment-processor/stripe-payment-processor-civicrm-42-15
