### ISSUE TITLE
CRM object does not exist in civicrm_stripe.js

### ISSUE THREAD

**Issue by thaeli** [drastik/com.drastikbydesign.stripe#31]
I'm running CiviCRM 4.4.3 on Wordpress 3.8.1. The Stripe integration version 0.7 works fine. However, when upgrading to trunk, I'm getting an error on the following line of civicrm_stripe.js:

```
Stripe.setPublishableKey(CRM.stripe.pub_key);
```

It seems that the CRM object doesn't exist on the page at all. Is this something related to the upgrade perhaps? The pub_key is present in the config panel and everything goes back to working properly when I restore the 0.7 version of the Stripe plugin files.

**Comment by drastik** [comment]
After upgrading, try flushing Civi's caches.  The old version used BillingBlock.tpl file to add JS, the new version uses Civi's new CRM. namespace to register the pub key.

**Comment by thaeli** [comment]
Flushing Civi's caches fixed the issue.

**Comment by eliotlandrum** [comment]
Me too on this one, and flushing caches didn't seem to help.

**Comment by lorenv** [comment]
Flushing the cache doesnt change "Stripe.setPublishableKey(CRM.stripe.pub_key);" from being able to get the pub key for me either. Very odd. Am going to try downgrading.

**Comment by lorenv** [comment]
Downgraded to 1.7 with 4.4.5 and its now working...odd.
