### ISSUE TITLE
Countries other than the USA cannot place orders

### ISSUE THREAD

**Issue by thaeli** [drastik/com.drastikbydesign.stripe#32]
While a "Country" field is displayed in the payment form, only the United States can be selected from the dropdown and the country field is not passed to Stripe.

**Comment by drastik** [comment]
Stripe wouldn't control which country fields are displayed.  That must be a setting elsewhere in CiviCRM.

**Comment by laryn** [comment]
Try /civicrm/admin/setting/localization?reset=1

**Comment by thaeli** [comment]
Aha, thanks! Fixed that and additional countries can now be selected from the dropdown. However, the Stripe plugin is still not actually passing the Country field to `Stripe.createToken`. I think this is a one-line fix in civicrm_stripe.js - will send a pull request later tonight.

**Comment by thaeli** [comment]
This was almost an easy fix, but CiviCRM is currently passing its internal ID's and not the ISO country codes into the dropdown of countries. Looks like we need to patch that list so that it also puts the ISO country code in an attribute.. Any suggestions on how to best do that?

**Comment by thaeli** [comment]
Closing this issue. The country is not currently passed to Stripe but I have confirmed that transactions from a UK credit card are successful with my US Stripe account.

**Comment by drastik** [comment]
Good.  It should be passing the currency code and I was hoping that was enough.
