### ISSUE TITLE
Persistent error: Stripe.js token was not passed! Have you turned on the CiviCRM-Stripe CMS module?

### ISSUE THREAD

**Issue by elliphant** [drastik/com.drastikbydesign.stripe#36]
Same error message that appeared in issue #28:

"Stripe.js token was not passed! Have you turned on the CiviCRM-Stripe CMS module?"

Running Civicrm_stripe 1.7, but also tried 1.8. Drupal 7.26, CiviCRM 4.4.4, PHP 5.4 (suppressed the strict warnings from issue #12).

I can't process any credit card contributions in test-drive mode. After I enter information and hit continue to contribute, the error pops up.  I'm not yet in a place where I can test the live mode.

One odd thing: I was successfully able to process one credit card contribution in test-drive.  After that one success, all other tries failed. (even after clearing all caches, uninstalling/installing the latest version/updating the API).

Thanks for any help.

**Comment by drastik** [comment]
I wonder if this is also related to ad-blockers.
Issues reported in other threads.
Main thread: https://github.com/drastik/civicrm_stripe/issues/45

Are you using AdBlock Plus or any other ad-blocking plugin?  If so, can you disable and give that a shot?

**Comment by wwatson13** [comment]
I was getting this same issue when trying to submit a payment through the admin membership form. with 1.8, Drupal 7.31 Civicrm 4.4.5, PHP 5.4.  I have reviewed all the other issues and nothing was working.  Looking at the code I found that the stripe token was not being loaded for the back office membership form so I added the following to the module and it worked.

  // For the 'Membership Record Contribution' backend page.
  if ($formName == 'CRM_Member_Form_Membership' && !empty($form->_processors)) {
    if (!isset($form->_elementIndex['stripe_token'])) {
      $form->addElement('hidden', 'stripe_token', NULL, array('id'=> 'stripe-token'));
      stripe_add_stripe_js($form);
    }
    // Add email field as it would usually be found on donation forms.
    if (!isset($form->_elementIndex['email']) && !empty($form->userEmail)) {
      $form->addElement('hidden', 'email', $form->userEmail, array('id'=> 'user-email'));
    }
  }

Immediately after I processed the payment there was an error about there being a network connection issue, however then the page automatically refreshed again with a message that the payment processed and the payment does show in the stripe dashboard.

**Comment by SebastianBowler** [comment]
We are getting a similar issue whilst trying to submit an event registration. The error message we receive is:

Stripe.js token was not passed! Report this message to the site administrator.

CiviCRM is on version 4.5.4, and Stripe is on 1.8. It's working fine for real payments through Stripe, so the problem only exists for us with test payments. The Stripe website account associated with the site does not register the test payment, though it does with the real.

**Comment by drastik** [comment]
@SebastianBowler  Drupal / Wordpress?

**Comment by SebastianBowler** [comment]
@drastik Drupal

**Comment by tttp** [comment]
do you have any js error messages on the page before the payment? 
On my side, I had to 
1) alter the resource url for extension (to put the relative path, as written in the doc)
2) re-generate the caches.

I'm using the 4.5 branch dev on a 4.4 civicrm, I had to change one line:

```
--- a/js/civicrm_stripe.js
+++ b/js/civicrm_stripe.js
@@ -6,6 +6,8 @@

   var $form, $submit, buttonText;

+  $ = $ || jQuery;
```

I'm going to submit a PR, but can't test right now on a 4.5 (don't have one with ssl)

**Comment by AlexTD56** [comment]
We're getting this error now, after a long period of perfectly fine operation. We're running Drupal and Civi 4.5.4. We used a page for our winter fund campaign and it worked fine through most of December, until it suddenly started throwing the 'Card cannot be blank' error - we didn't change anything on our end. I moved to the 4.5-dev branch to see if any recent changes would fix it, and now it's throwing the 'Stripe.js token was not passed!' error on live transactions. 

If there's likely to be useful diagnostic information, I'm happy to retrieve it and send it over. 

Would like to see this resolved, as we like Stripe when it works (rather than continually falling back to PayPal). Would be fine with tossing ~$200 (alone or as part of a larger bounty) to get some of the errors and kinks worked out on this.

**Comment by muhleder** [comment]
We've noticed we get this error when the submitOnce onclick gets attached to the form's submit button. It stops the stripe code picking up the form submit so the form gets submitted straight to Civi rather than having the call to the Stripe API fill out the token value first.

**Comment by muhleder** [comment]
Upgrading to 1.9.1 of this extension fixed the issue for us, the submitOnce isn't being attached to the payment form anymore.

**Comment by drastik** [comment]
@muhleder Good to hear!

This issue should be resolved in latest versions (1.9.1+).
Re-open if anyone is using the latest and still experiences this.

**Comment by seajaee** [comment]
@drastik I am getting this error [Stripe.js token was not passed! Report this message to the site administrator.] when using the Stripe processor with a real credit card number as well as a test credit card number on a live contribution page.  Also, I don't know how to write code. :(

CiviCRM 4.4.5
Wordpress 3.9.3
Stripe Extension 1.9.1

**Comment by dptarrant** [comment]
I am getting same error.   There is a cryptic instruction that appears after installation and then disappears regarding setting webhook.   Is there more information on what that means?

Using CiviCRM 4.5.5
Stripe 1.9.1

**Comment by drastik** [comment]
@dptarrant 
That information is just repeated from the "WEBHOOK" section of readme.
https://github.com/drastik/com.drastikbydesign.stripe#user-content-webhook

**Comment by dptarrant** [comment]
Thanks, for info on Webhooks

 still have the problem with
Stripe.js token was not passed!

Any troubleshooting suggestions?

Thanks

On Mon, Feb 9, 2015 at 10:44 AM, Joshua Walker notifications@github.com
wrote:

> @dptarrant https://github.com/dptarrant
> That information is just repeated from the "WEBFORM" section of readme.
> https://github.com/drastik/com.drastikbydesign.stripe#webhook
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drastik/com.drastikbydesign.stripe/issues/36#issuecomment-73530500
> .

## 

David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by seajaee** [comment]
Yes, I have the problem and my web hook is set properly.

Carmen

**Comment by Upperholme** [comment]
I'm using the latest release and not seeing this issue (on Drupal 7and Civi 4.5.5) what version are running?

**Comment by seajaee** [comment]
WP 4.1 / CiviCRM 4.4.5 and latest ver of the extension.

Carmen

**Comment by Upperholme** [comment]
I'm not clear if the latest version - 4.5-dev - or even 1.9.1 - is designed for Civi 4.4.x ? Others here might be able to clarify that.

**Comment by drastik** [comment]
CiviCRM Stripe 1.9.x is compatible with Civi 4.4.x and 4.5.x.

**Comment by dptarrant** [comment]
I am using

CiviCRM 4.5.5
Stripe Extension 1.9.1
Drupal 7.34

On Mon, Feb 9, 2015 at 11:45 AM, Upperholme notifications@github.com
wrote:

> I'm not clear if the latest version - 4.5-dev - or even 1.9.1 - is
> designed for Civi 4.4.x ? Others here might be able to clarify that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drastik/com.drastikbydesign.stripe/issues/36#issuecomment-73542523
> .

## 

David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by dptarrant** [comment]
Does this help?  Sorry for the details

Feb 09 11:14:07  [info] $backTrace = #0 /var/www/html/sites/all/modules/civicrm/CRM/Core/Error.php(387): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /var/www/html/sites/default/files/civicrm/custom/custom_ext/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php(235): CRM_Core_Error::fatal("Stripe.js token was not passed!  Report this message to the site administrator.")
#2 /var/www/html/sites/all/modules/civicrm/CRM/Contribute/BAO/Contribution/Utils.php(264): CRM_Core_Payment_Stripe->doDirectPayment((Array:53))
#3 /var/www/html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(1019): CRM_Contribute_BAO_Contribution_Utils::processConfirm(Object(CRM_Contribute_Form_Contribution_Confirm), (Array:53), (Array:38), "1", "1", "contribution", (Array:0))
#4 /var/www/html/sites/all/modules/civicrm/CRM/Core/Form.php(328): CRM_Contribute_Form_Contribution_Confirm->postProcess()
#5 /var/www/html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(162): CRM_Core_Form->mainProcess()
#6 /var/www/html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(60): CRM_Core_StateMachine->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next", "Next")
#7 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#8 /var/www/html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#9 /var/www/html/sites/all/modules/civicrm/CRM/Core/Controller.php(356): HTML_QuickForm_Page->handle("next")
#10 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(331): CRM_Core_Controller->run((Array:3), NULL)
#11 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(75): CRM_Core_Invoke::runItem((Array:15))
#12 /var/www/html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /var/www/html/sites/all/modules/civicrm/drupal/civicrm.module(457): CRM_Core_Invoke::invoke((Array:3))
#14 [internal function](): civicrm_invoke("contribute", "transact")
#15 /var/www/html/includes/menu.inc(517): call_user_func_array("civicrm_invoke", (Array:2))
#16 /var/www/html/index.php(21): menu_execute_active_handler()

**Comment by dptarrant** [comment]
I have successfully used Stripe Extension with another client installation.  So, I need to figure out the differences,  Both use the same versions so must be some config difference.  I will report back when/if I figure it out.

**Comment by seajaee** [comment]
@dptarrant

Thanks!

I will take another look too.

To Thine Own Self Be True

**Comment by dptarrant** [comment]
Found this error in ssl_error_log

[Tue Feb 10 22:01:54 2015] [error] [client xx.xxx.xx.xxx] client denied by
server configuration:
/var/www/html/sites/default/files/civicrm/custom/custom_ext/com.drastikbydesign.stripe/js/civicrm_stripe.js,
referer:
https://domain.org/index.php?q=civicrm/contribute/transact&reset=1&id=7

I have examined the httpd configuration and cannot find a solution.  Have
tried Allow All for the directory referenced in error but no luck

Does this error message suggest anything to the development team?

Thanks for help, I think I am going in circles without a flashlight.

On Mon, Feb 9, 2015 at 5:47 PM, seajaee notifications@github.com wrote:

> @dptarrant
> 
> Thanks!
> 
> I will take another look too.
> 
> To Thine Own Self Be True
> 
> On Mon, Feb 9, 2015 at 5:30 PM, dptarrant notifications@github.com
> wrote:
> 
> > I have successfully used Stripe Extension with another client
> > installation. So, I need to figure out the differences, Both use the same
> > versions so must be some config difference. I will report back when/if I
> > figure it out.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/drastik/com.drastikbydesign.stripe/issues/36#issuecomment-73604797
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drastik/com.drastikbydesign.stripe/issues/36#issuecomment-73607645
> .

## 

David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by drastik** [comment]
@dptarrant 
Double check this part:  https://github.com/drastik/com.drastikbydesign.stripe#user-content-installation

> Your CiviCRM 'Resource URLs' must be set to the extensions directory
> relative to Drupal/CRM base. Example: /sites/all/civicrm_extensions/
> NOT the full server path like /var/www/sites/all/civicrm_extensions/

It might re-write it after you save to something like:  `https://example.com/sites/all/civicrm_extensions`, which is fine.

So for you, this would be:  `/sites/default/files/civicrm/custom/custom_ext`

**Comment by dptarrant** [comment]
I had already checked that

https://domain.org//sites/default/files/civicrm/custom/custom_ext is the
setting (it does rewrite with the domain.org prefix)

On Tue, Feb 10, 2015 at 11:16 PM, Joshua Walker notifications@github.com
wrote:

> @dptarrant https://github.com/dptarrant
> Double check this part:
> https://github.com/drastik/com.drastikbydesign.stripe#user-content-installation
> 
> Your CiviCRM 'Resource URLs' must be set to the extensions directory
> relative to Drupal/CRM base. Example: /sites/all/civicrm_extensions/
> NOT the full server path like /var/www/sites/all/civicrm_extensions/
> It might re-write it after you save to something like:
> https://example.com/sites/all/civicrm_extensions/, which is fine.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drastik/com.drastikbydesign.stripe/issues/36#issuecomment-73831889
> .

## 

David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by dptarrant** [comment]
Still not solved.  I have had it working and then mysteriously it stops working.  Does this sound at all like the previous problems?

Thanks

**Comment by EranSch** [comment]
@drastik What are the potential causes for this that you can think of? I've got:
- Stripe.js doesn't get loaded
- JS Error on page prevents our JS from executing and thus form posts as usual with no token
- No classname present on the form for our JS logic to target, same issue as above occurs

Anything else come to mind?

**Comment by EranSch** [comment]
@dptarrant Do you see any errors in your browser's JS log when you get this error? If you're using Chrome, be sure to check 'Preserve Log' so the console doesn't clear out after each each page load. I'm sure there's an equivalent in all the others....

![image](https://cloud.githubusercontent.com/assets/1479206/6394029/a9ecd544-bd9c-11e4-90d7-1a02bafd2839.png)

**Comment by dptarrant** [comment]
Thanks for help.

So, strangely, it is working again.  And I am not sure why.

My current theory (as the error message in SSL error file seems to indicate) is that it is a permissions issue accessing the javascript.   Suspicion is that possibly it is because the directory is not allowed to access js files.   I am not a linux guy but it seems that there are .htaccess files that might be affecting the permissions and possibly (this is a stretch, I admit) there is some caching that is confounding me when I try to make changes and they don't work right away but then work later.   Does this make sense to anyone?

Thanks again.
