### ISSUE TITLE
1.8 not displaying as available extension in civicrm/admin/extensions

### ISSUE THREAD

**Issue by cacardinal** [drastik/com.drastikbydesign.stripe#39]
Hi @drastik - 

I've double checked to make sure that the resource paths are all correct. I tested them by installing another extension in the directory which was recognized immediately after refresh. 1.7 is now the only other extension that is installed. Are there any extra steps that I'm missing which aren't outlined in README/INSTALLATION?

**Comment by drastik** [comment]
Hi @cacardinal,

Just commented over on https://github.com/drastik/civicrm_stripe/issues/27

The info.xml file for 1.8 doesn't show 1.8 yet (still 1.7).  You probably have 1.8 installed if your contributions are working (on Civi 4.4+).  Sorry for the confusion.
