### ISSUE TITLE
4.2 - 1.4:  seeing false error message 

### ISSUE THREAD

**Issue by ghost** [drastik/com.drastikbydesign.stripe#4]
Configuration:
- Stripe paymet enabled
- pay later option enabled

To reproduce:
- on event registration page, select Stripe option
- change mind and select pay later option
- click continue

Result:
- error message about Credit card: "exp_year should be integer (instead is undefined)"

Expectation:
- credit card processing would not apply, pay later option is active

**Comment by drastik** [comment]
Fixed pay later & 4.3 compatibility.
http://civicrm.org/extensions/stripe-payment-processor/stripe-payment-processor-civicrm-42-15

**Comment by ghost** [comment]
This seems to have regressed and is again a problem.  4.4.3 + 1.6
