### ISSUE TITLE
Flashing payment warning

### ISSUE THREAD

**Issue by iaminawe** [drastik/com.drastikbydesign.stripe#40]
After a fair amount of wrestling I have donations processing again using the 1.8 version of this module with CiviCRM 4.4.5 and the v2 version of the stripe API

The following error/warning message flashes every time when you submit the donation form

Payment Error Response:
- Error: An unexpected error has occurred submitting your credit card to
  our secure credit card processor. This may be due to network connectivity
  issues, so you should try again (you won’t be charged twice). If this
  problem persists, please let us know!

But the error doesn’t stop the transaction and it proceeds correctly to the payment page
This can be seen here https://www.fcpp.org/civicrm/contribute/transact?reset=1&id=1

**Comment by laryn** [comment]
@iaminawe See this and let us know if it makes a difference in your case as well: https://github.com/drastik/civicrm_stripe/issues/27#issuecomment-47481177

**Comment by iaminawe** [comment]
Yes I can confirm that by disabling Adblocker Plus, I no longer see the flashing message. Thanks.

**Comment by laryn** [comment]
Thanks for confirming @iaminawe 

@drastik If we can figure out whether some JS is getting caught up in the default AdBlock Plus net perhaps there is some way we can rename the file to avoid triggering the standard adblocking screens and wildcard matches, to avoid this issue for other end users that may have AdBlock installed?

**Comment by drastik** [comment]
Looks like the Ad Block issue might be something that has to go all the way up to them.

I was searching around for it effecting Stripe in general (not just Civi), and I got a positive hit.  A similar plug in "NoScript" had a patch with notes: "Fixed false positive on redirected script inclusions ... for Stripe payments".

http://noscript.net/changelog#2.6.8.5

**Comment by drastik** [comment]
I think the Ad Block situation deserves it's own issue here on github.  I will make a note in the README as well.

**Comment by drastik** [comment]
Ok, I made a post on ad block's bug reporting forum:
https://adblockplus.org/forum/viewtopic.php?f=17&t=23836

**Comment by drastik** [comment]
Created a thread about ADP, updates on that situation will go there:
https://github.com/drastik/civicrm_stripe/issues/45

**Comment by eliotlandrum** [comment]
Thanks for all the action on this @drastik. I put on my forms a big warning that my customers need to disable all ad or script blocking plugins if they have any troubles.

**Comment by drastik** [comment]
Closing these old issues to get some order in the queue.

Please open & update if this issue exists using the latest (4.5-dev) branch (yes, even if your CiviCRM is 4.4.x).
