### ISSUE TITLE
Errors if confirmation page is not selected

### ISSUE THREAD

**Issue by iaminawe** [drastik/com.drastikbydesign.stripe#41]
I have donations processing again using the 1.8 version of this module, the stripe-php library, CiviCRM 4.4.5 and the v2 version of the stripe API

I found that if I did not enable the confirmation page, I would receive either a WSOD on submitting the donation or the following error messages

![frontier donation error june 3 2c 2014](https://cloud.githubusercontent.com/assets/725813/3167769/e451d01e-eb73-11e3-8b6f-31ca78af5467.PNG)

**Comment by laryn** [comment]
@iaminawe See this and let us know if it makes a difference in your case as well: https://github.com/drastik/civicrm_stripe/issues/27#issuecomment-47481177

**Comment by iaminawe** [comment]
I disabled Adblocker Plus, disable "Use confirmation screen" and try and resubmit a donation.Unfortunately I still receive the WSOD in this case.

**Comment by laryn** [comment]
Unfortunately, same here. I forgot to test this setting earlier... 
`You cannot set 'card'to an empty string. We interpret empty strings as NULL in requests. You may set obj->card = NULL to delete the property`

**Comment by drastik** [comment]
Looks like the Ad Block issue might be something that has to go all the way up to them.

I was searching around for it effecting Stripe in general (not just Civi), and I got a positive hit.  A similar plug in "NoScript" had a patch with notes: "Fixed false positive on redirected script inclusions ... for Stripe payments".

http://noscript.net/changelog#2.6.8.5

**Comment by drastik** [comment]
Closing these old issues to get some order in the queue.

Please open & update if this issue exists using the latest (4.5-dev) branch (yes, even if your CiviCRM is 4.4.x).
