### ISSUE TITLE
AdBlock Plus breaks payments (Browser plugin for FireFox and others)

### ISSUE THREAD

**Issue by drastik** [drastik/com.drastikbydesign.stripe#45]
An issue has been reported in their forums (according to their bug reporting policy).
https://adblockplus.org/forum/viewtopic.php?f=17&t=23836

**Comment by eliotlandrum** [comment]
Awesome, thanks @drastik !

**Comment by iaminawe** [comment]
Thanks @drastik

**Comment by drastik** [comment]
Over on that forum post, they are asking for:
"Can you submit an Adblock plus report link here? (when it occurs)"

Anyone have this or know what that is?

**Comment by drastik** [comment]
I am no longer having AdBlock Plus issues.

Please re-open if there is still a problem.

**Comment by ConstantinChirila** [comment]
Hey @drastik , how did you solve the issue?
I still have this problem, stripe seams to block any external files coming from stripe.com
