### ISSUE TITLE
CiviCRM 4.5 compatibility

### ISSUE THREAD

**Issue by chanunc** [drastik/com.drastikbydesign.stripe#46]
Hi
I just fixed some issue when using this extension with CiviCRM 4.5 beta 4.
Could you add new branch for 4.5 then I can send pull request to,

Thanks

**Comment by drastik** [comment]
Somehow I missed this comment.

Adding now.

**Comment by drastik** [comment]
https://github.com/drastik/civicrm_stripe/tree/4.5-1.8
