### ISSUE TITLE
Pay Later problem (Civi4.3, Civi-Stripe 1.6)

### ISSUE THREAD

**Issue by laryn** [drastik/com.drastikbydesign.stripe#5]
Hi Joshua,

I just installed this (v1.6) via the Civi extension manager on a site (CiviCRM 4.3.3) and on a contribution page with the option to pay later I get this (when I try to use the pay later): 

`The 'exp_year' parameter should be an integer (instead, is undefined).`

Looks like it's still running through Stripe even though Pay Later is selected? I think there was a similar issue in an earlier version but the thread was closed so I'll post here again.

**Comment by drastik** [comment]
I'm wide open to ideas.  I can't replicate this on my demo site as of the changes from last time.

Do you have (or can you make) a demo site with the problem where I can play w/ it?

What a frustrating issue :(

**Comment by laryn** [comment]
I'll see if I can open this up on a demo site. At the moment I've just disabled 'Pay Later' on the live site...

**Comment by drastik** [comment]
Any news?

**Comment by laryn** [comment]
Sorry on the demo site front, I've been kind of swamped. I did refine the bug report a little bit, however, so let me know if this helps: 

If I activate Stripe, Paypal, and Pay Later and Stripe is the default, both Paypal and Pay Later give the error. If I make PayPal the default, paying through PayPal does not give the error right off the bat, but it does give the error if I select Stripe and then reselect PayPal.

Seems to me that templates/CRM/Core/BillingBlock.tpl adds Stripe's js in if Stripe is the default (or if Stripe gets selected) and it remains in place even if another payment processor is selected. Line 29 does that check to make sure Stripe is selected but I guess we need something to remove or disable that javascript if Stripe is deselected?

L.

**Comment by laryn** [comment]
Here's a sample hard-coded hack that seems to work for me. Hopefully there is a more elegant way to do this. (Stripe is payment processor id #3 in my site):

https://github.com/CEDC/civicrm_stripe/compare/drastik:4.2-1.6...4.2-1.6

**Comment by drastik** [comment]
I see.  Yes, the way that area is handled is not desirable, however Civi didn't provide any steady machine_name identifiers for the current payment processor selected.

I think to better support this, we need a Civi core change to add some sort of unique identifier to a payproc's  payment options attributes. (or something along these lines).

**Comment by laryn** [comment]
One other thought -- I haven't used the Javascript for CiviCRM's API much, but could we use that to pull the IDs for any Stripe payment processors and then check if the value of payment_processor is any of those?

e.g. 
CRM.api('PaymentProcessor', 'get', {'sequential': 1, 'class_name': 'Payment_Stripe'},
  {success: function(data) {
      cj.each(data, function(key, value) {// do something });
    }
  }
);

**Comment by ghost** [comment]
I'm seeing this problem (exp_month) error when switching from Stripe (only payment processor registered) and pay later option.  I'm on Civi 4.4.3  + WP 3.7.1  with the newest civicrm_stripe extension loaded.
http://roaringsky.clarify-it.com/d/6nhlmy
As I recall, Joshua, this is a regression of a problem you resolved (in coversation with me) on the 1.4 + 4.27 line.

**Comment by iaminawe** [comment]
I am also still seeing this using CiviCRM 4.4.5 | v2 Stripe API | 4.4-1.8 - I receive the Error: The 'exp_month' parameter should be an integer (instead, is undefined). 

I tried adjusting the payment method check as suggested previously above
https://github.com/CEDC/civicrm_stripe/compare/drastik:4.2-1.6...4.2-1.6

I have tried a variety of things but still seem to consistently get that same error

**Comment by andy-walker** [comment]
We were getting this as well - have submitted a pull request with a proposed fix here:
https://github.com/drastik/civicrm_stripe/pull/47
