### ISSUE TITLE
Optionally use frontend validation to eschew need for PCI compliance?

### ISSUE THREAD

**Issue by EranSch** [drastik/com.drastikbydesign.stripe#56]
One of the best things about Stripe is that it enables payments to be made without the need for PCI compliance. This is easy to implement when building a payment form from scratch however more complex when dealing with CiviCRM. 

![screen shot 2014-10-01 at 4 25 52 pm](https://cloud.githubusercontent.com/assets/1479206/4482489/281306ea-49a9-11e4-8bcd-af2fdcf17d9e.png)
_CC data POSTed to server_

The simple way to carrying out a payment without CC info hitting the server is to remove the `name` attributes from sensitive fields. This way Stripe.js sends the sensitive data over SSL to Stripe, Stripe returns a token, and the token is POSTed back to the server which uses it to commit the payment.

The problem with suppressing sensitive fields from the POST to the server is that Civi likes to do server-side validation of the submitted information, which goes against this whole concept-- hence _this_ issue.
## Optional Frontend Validation

What I'm envisioning would be an option within the Payment Processor's settings to toggle between JS or server-side validation. The former option would allow a site to responsibly accept payments without requiring PCI compliance. 

As far as I can tell, this requires several things...
- CiviCRM's server-side validation must be disabled
- CC Type and validity must be confirmed with on-page JS
- Confirmation page either must be generated with JS or maybe by passing the Stripe token through the server to the confirmation page?
- ???

I'm up for working on implementing this but I'd love some feedback/help fleshing out an implementation as I'm not that familiar with developing for CiviCRM :sweat_smile:

**Comment by drastik** [comment]
I talked with someone about this briefly in the past.

I think if we passed it to Stripe, then obfuscated the card details before passing to Civi (but still passing values), it might be a solution.

Think: 4111111111111111  or, if possible:  xxxxxxxxxxxx1234

**Comment by EranSch** [comment]
That seems pretty reasonable. Is there an established means for preventing Civi from attempting to validate CC info and instead _just_ accepting it?

**Comment by drastik** [comment]
If memory serves, I think it does very basic validation (number of characters correct, numeric only, etc).
Not whether it is actually a valid number though.

Needs investigation though.  I've been out of the Civi world for a couple years now, but I'll be getting involved again very shortly.

**Comment by drastik** [comment]
Haha @Swingline0,
This change was included in Kurund's commit @ #57 

Just merged.

**Comment by EranSch** [comment]
@drastik I'd say this issue should be reopened as we've found that dummy data route adds a host of new problems and has been reverted.

**Comment by drastik** [comment]
We can't pass card data to the server, but I'm thinking there is a way we can persist a stripe token and check for it on validation pages (or if an issue occurs, and it needs to re-present the contrib form) -- then we can look for the token and use that.

2 issues:
1) We won't be able to actually fill in the CC form fields, because we just have the token.  We could drop a semi-transparent overlay on it and say something to the effect of "Use same card or Edit card".
2) Stripe tokens were 1-time use.  I don't know if this is still the case, or if there is some other token-type option. 

I am reading up on their API today to find out.  A lot has changed.
