### ISSUE TITLE
Poor selector in JS

### ISSUE THREAD

**Issue by EranSch** [drastik/com.drastikbydesign.stripe#60]
Also in testing #57.

The jQuery selector for the submit button was changed and I'm not sure why. The new selector...

``` js
$("input[type='submit']:last").click();
```

This seems quite vague and (in WordPress at least) doesn't even target the correct element. What's the purpose here, @kurund ?

I'll submit a PR for this and few other issues this morning. Just wanted to open the discussion. :smile:

**Comment by EranSch** [comment]
Furthermore, using `$.click()` here doesn't seem to work as the event is terminated by the submit listener we've already applied to the form. This then attempts to generate a new Token except it then uses the dummy CC data.

**Comment by kurund** [comment]
@Swingline0 yes, my bad, it worked for anonymous user, I missed to check it for logged in user. selector is bit vague, thanks for pointing it ..

**Comment by EranSch** [comment]
Sure thing!
