### ISSUE TITLE
Redirect loop on card errors

### ISSUE THREAD

**Issue by EranSch** [drastik/com.drastikbydesign.stripe#62]
For the most part things are running very smooth. A contribution form seems to work perfectly with and without a confirmation page. 

I seem to be getting stuck in a redirect loop, however, when I use test CC numbers to trigger various errors. For example, the credit card number `4000000000000002` will ["be declined with a card_declined code."](https://stripe.com/docs/testing#cards).

When I submit a payment with this number, the token is retrieved correctly and the form submits but it seems that when the extension attempts to charge the number and redirect back to the payment form, a redirect loop begins...

![redirect](https://cloud.githubusercontent.com/assets/1479206/4493041/3e335194-4a46-11e4-8721-2af1dc9cb774.png)

If I clear the error and return to the original contribution page, I see the indended error:

![screen shot 2014-10-02 at 11 13 27 am](https://cloud.githubusercontent.com/assets/1479206/4493092/a7276d2a-4a46-11e4-91d1-339c8c9f45cc.png)

I'm not sure where to look here or how this works in the other frameworks but I'll keep searching. 

WordPress 4.0
CiviCRM 4.5
Using 4.5-1.8 Branch

**Comment by drastik** [comment]
This has cleared up in latest versions right?

**Comment by EranSch** [comment]
I don't believe it has but I haven't tested it recently. I'll see if I can
do so today.

**Comment by EranSch** [comment]
Nope. Still very much an issue. I'm synced up with the dev branch and I disabled/enabled the extension prior to testing. Furthermore, this issue seems to occur regardless of whether or not the confirmation page is enabled. I think that was just crummy testing on my part.

I'm using a contribution page with the following test CC number: `4000000000000002`

Are you able to reproduce the problem?

**Comment by EranSch** [comment]
It looks like this is being caused by the if/else statements in [`CRM/Core/Payment/Stripe.php`](https://github.com/drastik/civicrm_stripe/blob/4.5-1.8/CRM%2FCore%2FPayment%2FStripe.php#L198) that attempt to infer what civi path the user should be redirected to on error:

``` php
      if (empty($params['selectMembership'])
        && empty($params['contributionPageID'])
      ) {
        $error_url = CRM_Utils_System::url('civicrm/event/register',
          "_qf_Main_display=1&cancel=1&qfKey={$qfKey}", FALSE, NULL, FALSE);
      }
      else {
        $error_url = CRM_Utils_System::url('civicrm/contribute/transact',
          "_qf_Main_display=1&cancel=1&qfKey={$qfKey}", FALSE, NULL, FALSE);
      }
```

Dumping the `$params` array reveals neither of the indexes used in the if condition are present during a frontend contribution or membership registration. As a result, the `'civicrm/event/register'` path kicked things off to a bad start that seemingly resulted in a redirect loop.

In the case of my environment (WordPress :wink:), the correct civi path is available in the `$_REQUEST` array within the index `q` -- thus fc2544bbf43c6a84b5a16f0aa19474fa0cd2da76 resolves this issue through and through. 

Problem is, I'm not sure if this is a WordPress-specific array index or not. What do you think?

**Comment by drastik** [comment]
Try with latest in 4.5-dev branch as of today.  Reworked the error url stuff and other things.
I tested all user-facing forms with good and bad cards and had no issues.

https://github.com/drastik/civicrm_stripe

**Comment by EranSch** [comment]
The new error url strategy introduces a new problem on WordPress. Essentially, the url that comes out is malformed and a permission error comes out. Here's how the parse url breaks down from wordpress:

```
Array ( 
  [scheme] => http 
  [host] => [omitted] 
  [path] => /become-a-member/ 
  [query] => page=CiviCRM&q=civicrm/contribute/transact& 
)
```

The resulting URL is something along the lines of:

http://[ommitted]/become-a-member/?page=CiviCRM&q=become-a-member/&_qf_Main_display=1&qfKey=[...]

I'm not sure how specific this is to wordpress but the path itself is only used to derive the page on which the actual civi content is displayed. Evidently there is a sharp difference between Drupal's path and WP's.

**Comment by drastik** [comment]
Alright @Swingline0 , I just made another change which should fix the issue mentioned in your last comment.

Please open & update if this issue exists using the latest (4.5-dev) branch (yes, even if your CiviCRM is 4.4.x).
