### ISSUE TITLE
Dummy CC data displayed to user when returned to payment form after error

### ISSUE THREAD

**Issue by EranSch** [drastik/com.drastikbydesign.stripe#63]
Once again, testing #57.

I'm using an Amex number which is not an enabled card type. Stripe generates the token as expected and the transaction continues. The issue, it seems, is that the user is redirected back to the payment form where the error message is displayed. This is awesome however the dummy data is shown:

![card-type-numbers3](https://cloud.githubusercontent.com/assets/1479206/4493359/d3a1d8d4-4a48-11e4-8fb3-ae29320ad4ec.gif)

I think the best way to clean this up would be clear the fields entirely rather than allow them to be prepopulated.

Where would the best place to this be? Is there a way to do it in PHP or is it better to detect the error state in the JS and clear it then?

_Sidenote: I was suspecting that the change to use dummy CC details when posting the form back to Civi would prevent the allowed card types from being enforced. I was wrong, however, it appears this wrks correctly which is awesome!_

**Comment by eliotlandrum** [comment]
I am having the dummy data filled in without even going forward to the Processing state (Confirm is not doing anything). I should start a new issue, but so far the latest merge #57 is not working at all for me. :(

**Comment by EranSch** [comment]
Being that the dummy data has been reverted in the last PR, I'll go ahead and close this issue.
