### ISSUE TITLE
include packages in extension

### ISSUE THREAD

**Issue by eileenmcnaughton** [drastik/com.drastikbydesign.stripe#69]
Given that Composer isn't being use properly in CiviCRM extension system and that CiviCRM normally ships extensions & core with packages included I think it makes sense to include the stripe package in the extension.  The alternative is not -upgrade proof

 I've added this to my pull request - it adds packages into the extension & also adds it to the path

https://github.com/drastik/civicrm_stripe/pull/68

**Comment by drastik** [comment]
Committed, thanks.
