### ISSUE TITLE
1.6 to 1.7 upgrade

### ISSUE THREAD

**Issue by awkale** [drastik/com.drastikbydesign.stripe#8]
I recently uploaded the new extension but civicrm is telling me to upgrade to 1.6 even though I have 1.7.

any ideas why this is happening? should I ignore it?

![screen shot 2013-09-02 at 8 18 46 am](https://f.cloud.github.com/assets/744487/1067274/045ce4f2-13ca-11e3-828d-d864e54baaeb.png)

**Comment by drastik** [comment]
Yes ignore. I haven't created the new 1.7 release on civicrm.org so it doesn't understand.
