### ISSUE TITLE
Multiple recurring donations

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#88]
I've run into an issue with CiviCRM recurring donations.

If someone makes a recurring donation it doesn't add the recurring donation it replaces their existing recurring donation.  Anyone else run into this problem and/or know of fix or work around?

**Comment by laryn** [comment]
I haven't tested thoroughly but did note that in test mode it seemed that when I made multiple test recurring donations it didn't show up as multiple transactions but I can't recall if that was a Stripe issue or a CiviCRM issue.

**Comment by DaveBagler** [comment]
I'll have to do some playing around with it.

**Comment by rajeshrhino** [comment]
@DaveBagler Did you find any solution for this issue? 

Looks like the issue is with the extension, where it over writes the card details, if the customer already exist in Stripe.

**Comment by drastik** [comment]
When Stripe came out, they only allowed 1 card per customer, and 1 "subscription" (recurring payment) per customer.

I think they have since made updates that allow multiple, and the extension needs updated accordingly.
