### ISSUE TITLE
USD is forced for recurring plans

### ISSUE THREAD

**Issue by DaveBagler** [drastik/com.drastikbydesign.stripe#9]
When ever I try to submit a monthly donation I get the following error: (example is for $10 monthly)

<code>No such plan: month-1000</code>

Do each of the plans need to exist as a subscription in Stripe before they can be used by civicrm? And if so do you have any advice for supporting an "other amount" option with the monthly donations?

**Comment by drastik** [comment]
No, it should check if the plan exists first, and use if exists, otherwise create it if not.

Any amount should be accepted fine (including "other" fields) since the plans are built with a simple id: 'frequency-amount'.

See here:  
https://github.com/drastik/civicrm_stripe/blob/4.3-1.7/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php#L403-L434

**Comment by DaveBagler** [comment]
Thanks for the quick response.  That was my understanding but whenever I submit a monthly donation I get the following error: (this one is a $10 monthly)

![civi-error](https://f.cloud.github.com/assets/3266985/1185798/a922ac3e-22c9-11e3-97eb-dfd56b3a3ee7.png)

**Comment by DaveBagler** [comment]
I've contacted Stripe about this and I'll update this issue if they have any advice or insight.

**Comment by DaveBagler** [comment]
OK, I've sort of figured it out.  As it turns out the problem causing the "No such plan:" message was that I'm using CAD with Stripe and the plugin forces the recurring donation to be in USD:

https://github.com/drastik/civicrm_stripe/blob/4.3-1.7/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php#L423

Now, I just need to sort out this error, that I now receive after submitting a recurring contribution:

![newerror](https://f.cloud.github.com/assets/3266985/1188550/92ca3734-23d9-11e3-8403-ed6b9d649a42.png)

**Comment by DaveBagler** [comment]
Turns out the issue above is due to a lack of error checking on installments.  I'll create it as a separate issue.  Also I'll update the title for this issue to reflect what's really happening.

**Comment by drastik** [comment]
This was fixed last commit.

https://github.com/drastik/civicrm_stripe/commit/dcc56aecfeac9d7286ced46c9e947407fd590502
