### ISSUE TITLE
Multi-currency payment handling

### ISSUE THREAD

**Issue by Upperholme** [drastik/com.drastikbydesign.stripe#91]
I'm working with an international charity on a new CiviCRM implementation. They want to be able to provide online donors with a choice of which currency they want to use to make a donation.
The information provided by Stripe indicates that they can accept payments in a wide range of currencies, which they then exchange into the currency supported by my client's linked bank account.
What I'm not clear on is:

a) How and whether CiviCRM itself supports and handles multiple currencies beyond simply making numeorus currencies available via the localization configuration. e.g. are contributions recorded as currency specific amounts in the Civi database and handled accordingly. (I'm not looking for answers to these questions here, but if anyone knows, don't hold back :-) (see also the related stackexchange post and responses here: http://civicrm.stackexchange.com/questions/3708/how-can-i-create-a-contribution-page-that-allows-the-user-to-select-the-currency

b) Does the Stripe payment processor handle currency information and pass it to Stripe effectively?

Thanks for any help on this.

**Comment by drastik** [comment]
b) Yes, this payproc will take the currency code from CiviCRM and pass to Stripe.
Just be sure to double check the supported currencies within Stripe:
https://support.stripe.com/questions/which-currencies-does-stripe-support

**Comment by Upperholme** [comment]
Just about to begin testing this, so this is great news, thanks.

**Comment by Upperholme** [comment]
It's been a while, but we now have some live transactions coming through, and it looks like the data being submitted to stripe.com is not providing the correct currency information.

Background: Wordpress site, CiviCRM 4.6.x, Stripe extension version 1.9.1 is reported, and the directory in my extensions folder is called com.drastikbydesign.stripe-4.6-dev (installed in June/July).

Civi is configured with GBP as the default currency, and GBP, USD and EUR are all set as available currencies. We have - at present - three contribution pages, one for each of the three currencies, and the currency is set in the configuration for each page.

CiviCRM is recording the transaction in the correct currency (USD). Stripe is recording the transaction, but is recording it in GBP. This is causing a major issue as you might expect. We have a user who has donated USD20. CiviCRM tells us they have donated USD20, but Stripe has read this as GBP20, and taken USD31.64 from the user's credit card. Not good.

Looking at the events and logs data in the Stripe dashboard I can see that 'gbp' is being given everywhere as the currency.

I don't know if this is a bug in this extension or more generally in CiviCRM, but my guess - and it is a guess - is that the currency data is being taken from the default currency rather than from the currency that is set for the specific contribution page.

I'll put through some test transactions in all three of the currencies we are working with, and will report anything useful back into this thread. I'll also check the Civi issue queue and see if there's anything there.

Any help on this would be really useful as we are in a live situation and I don't want to have to disable these contribution pages if I can avoid it, given the impact on my client's donations.

**Comment by Upperholme** [comment]
Would this issue have a bearing here? https://issues.civicrm.org/jira/browse/CRM-16845

**Comment by drastik** [comment]
Yikes!
Well, you can see in civicrm_stripe's code where it is trying to pull the Currency ID:
https://github.com/drastik/com.drastikbydesign.stripe/blob/4.6-dev/CRM/Core/Payment/Stripe.php#L475

If you want to check for any other variables that might contain a different Currency ID, you can do a variable dump anywhere in doDirectPayment(), first line is fine:
https://github.com/drastik/com.drastikbydesign.stripe/blob/4.6-dev/CRM/Core/Payment/Stripe.php#L254

Set up a debug / dump (or log, not familiar with what WP has to offer), run some test mode transactions, and see if you have any other options.  Please let me know if you come up with anything and we'll get this updated ASAP.

**Comment by Upperholme** [comment]
Thanks for getting back on this. I've run a whole series of test transactions in all three currencies that I'm using and can't replicate the problem that I've seen with two live transactions so far, although I'm having problems getting recurring transactions to complete in test mode (see this issue for more on that one: https://github.com/drastik/com.drastikbydesign.stripe/issues/96), and both of the problematic live transactions were recurring.

**Comment by Upperholme** [comment]
The latest changes have resolved this problem with recurring payments and currency so I'm closing this one. Thanks
