### ISSUE TITLE
One of parameters  (value: NULL) is not of the type Integer

### ISSUE THREAD

**Issue by jmcclelland** [drastik/com.drastikbydesign.stripe#92]
I'm seeing this repeated throughout my ConfigAndLog file.

Here is the code that is throwing the error:

```
        $query_params = array(
          1 => array($recur_contrib_query->contact_id, 'Integer'),
          2 => array($recur_contrib_query->{$financial_field}, 'Integer'),
          3 => array($recur_contrib_query->payment_instrument_id, 'Integer'),
          4 => array($recieve_date, 'String'),
          5 => array($total_amount, 'String'),
          6 => array($fee_amount, 'String'),
          7 => array($net_amount, 'String'),
          8 => array($transaction_id, 'String'),
          9 => array($new_invoice_id, 'String'),
          10 => array($recur_contrib_query->currency, 'String'),
          11 => array($recur_contrib_query->id, 'Integer'),
          12 => array($recur_contrib_query->is_test, 'Integer'),
          13 => array($recur_contrib_query->campaign_id, 'Integer'),
        );
        CRM_Core_DAO::executeQuery("INSERT INTO civicrm_contribution (
          contact_id, {$financial_field}, payment_instrument_id, receive_date,
          total_amount, fee_amount, net_amount, trxn_id, invoice_id, currency,
          contribution_recur_id, is_test, contribution_status_id, campaign_id
          ) VALUES (
          %1, %2, %3, %4,
          %5, %6, %7, %8, %9, %10,
          %11, %12, '1', %13)",
          $query_params);
```

I tested all the parameters and discovered that it is campaign_id that is not an integer.

This problem seems caused in line 93:

```
        if (empty($recur_contrib_query->campaign_id)) {
          $recur_contrib_query->campaign_id = 'NULL';
        }
```

I'm working on a patch that sets campaign_id to 0 if it's empty so it is an integer.

**Comment by jmcclelland** [comment]
btw, all line numbers are reference the 4.5 version.

**Comment by jmcclelland** [comment]
I've just updated by pull request. We get a constrain error if we try to insert a campaign id of 0. So, re-factoring the fix to insert either NULL or the campaign id.

**Comment by jmcclelland** [comment]
I see that my final update to the pull request never made it (I think that's because the original one was merged already). This issue has been raised again in #117 so I'm closing it here and will follow up there.

**Comment by h-c-c** [comment]
I'm not sure how to approach the FK constraint problem.  But, the default behavior for CiviCRM is that contributions do not have a campaign_id unless explicitly added.  The default is actually NULL....I can see this in my civicrm_contributions table.   So shouldn't the default parameter for key 13 be NULL and not Integer?

```
13 => array($recur_contrib_query->campaign_id, 'NULL'),
```

Sorry if this is a dumb question, but would this trigger an error or otherwise be bad if campaign_id was set to an integer later on?

**Comment by jmcclelland** [comment]
CiviCRM's Database object takes parameters in the form of a value (in the case of the line above, the value is $recur_contrib_query->campaign_id) and the type of value that it should be restricted to.

In other words, if you say the value will be an Integer, then the database query won't be run if the value you are passing is not an integer.

That's why the initial code failed - because sometimes NULL is passed in as the campaign id (when no campaign is set) and sometimes an integer is passed in (when a campaign is set). SInce NULL is not an integer, we get an error.

If you set it to NULL, though, it will fail if you have a campaign id that is an integer.

So - you can't win using this method.

My patch avoids the method altogether so we can have either NULL or an integer by validating the value manually and not using CiviCRM's type checking

**Comment by h-c-c** [comment]
Cool, thanks for explaining.

**Comment by drastik** [comment]
Our end goal for this is to remove all of these manual queries and replace with `civicrm_api()` calls.
